#+TITLE: Internee Outcomes: Data Analysis
#+PROPERTY: header-args:R: :session *R:internment* :export both :colnames yes

#+begin_src R :results silent :session *R:internment*
library(tidyverse)
library(duckdb)
library(haven)
library(fixest)
library(ggplot2)

library(targets)

tar_source()
tar_load(c(wage_sample))

setFixest_etable(
  style.tex = style.tex("aer"),
  postprocess.tex = NULL
)

etable_dict <- c(
  "reset", # to reset global dict 
  INCWAGE_1950="Income in 1950", INCWAGE_1940="Income in 1940",
  INCTOT_1950="Total Income", INCBUSFM_1950="Bus./Farm Income", INCOTHER_1950="Other Income",
  int_prob="$\\hat{E}[I|county,race]$", age_adj_1950="Age", 
  sex_adjMale="Male", race_adjJapanese="Japanese", 
  EDUCD_1950="Education",
  STATEFIP="State", STATEFIP_1950="State$_{1950}$", STATEFIP_1940="State$_{1940}$",
  COUNTYICP="County", COUNTYICP_1950="County$_{1950}$", COUNTYICP_1940="County$_{1940}$",
  HRSWORK1_1950="Hours worked", HRSWORK1_1940="Hours worked$_{1940}$",
  WKSWORK1_1950="Weeks worked", WKSWORK1_1940="Weeks worked$_{1940}$",
  OCCSCORE_1950="Occ. score", 
  employed_1950="Employed",
  change_occ="Occ. change",
  county_intprop="$\\hat{E}[I|county]$", intprob_AB="$\\hat{E}[I_i|state, bpl, byr, race]$",
  intprob_full="$\\hat{E}[I|county, sex, bpl, byr, race]$"
)

#+end_src

* MLP Linked Internees
:PROPERTIES:
:header-args:R: :session *R:internment*
:END:
** Linked Sample Size
I want to focus on the Japanese and Chinese populations as the main treatment and control groups of my study.
However, it's not as simple as just filtering on race status in one reference year.
There are many linked individuals who report different racial categories across the different census years.
This may be due to transcription errors, differences in census takers, false matches in the MLP linking process, etc.

#+begin_src R
tbl(con, mlp_tbl) |>
  count(YEAR, RACE) |>
  collect() |>
  ipumsr::set_ipums_var_attributes(var_info = ipumsr::read_ipums_ddi(ddi_mlp)) |>
  mutate(RACE = as_factor(RACE)) |>
  pivot_wider(names_from = RACE, values_from = n)
#+end_src

#+RESULTS:
| YEAR |    White | Black/African American | American Indian or Alaska Native | Chinese | Japanese | Other Asian or Pacific Islander | Other race, nec |
|------+----------+------------------------+----------------------------------+---------+----------+---------------------------------+-----------------|
| 1940 | 68426104 |                5006313 |                           144394 |   20882 |    52930 |                           13855 |             237 |
| 1950 | 68444757 |                5052709 |                           110224 |   13146 |    35008 |                            7797 |            1074 |

Notice how almost all of the individuals who are reported as White are consistently White across years,
but the number of linked individuals who are Chinese or Japanese decrease significantly in 1950.
This may be because the 1950 full-count census data are more recent and still being worked on,
so for now it's probably safest to use the 1940 =RACE= status to assign race in my study.

Based on this, there are 73,812 linked individuals who report being either Japanese or Chinese in 1940
(and potentially some other race in 1950).


The match rate for this population is a little less than the ~55% match rate in the MLP linkages overall.
Based on the numbers in the table above, the match rate for Japanese/Chinese respondents is 73,812 / 204,906 ≈ 36%.

| Source:  | Year | Total   | Japanese | Chinese | Japanese + Chinese |
|----------+------+---------+----------+---------+--------------------|
| Census   | 1940 | 132.9 m |   126701 |   78205 |             204906 |
|          | 1950 | 152.3 m |   278603 |  119522 |             398125 |
|----------+------+---------+----------+---------+--------------------|
| MLP v2.0 | 1940 | 73.7 m  |    52930 |   20882 |              73812 |
|          | 1950 | 73.7 m  |    35008 |   13146 |              48154 |

For my main analysis on the growth of incomes among this group,
I select only those individuals who would have been of working age in 1940 and thus able to have worked a job in both years observed.
This means that I filter the MLP sample for anyone born before 1926.
Someone born in January of 1926 would have been 13 in the year 1939
making them too young to be asked about their earnings or employment when surveyed in 1940.
#+begin_src R
j_c_sample <- tbl(con, mlp_tbl) |>
  pivot_wider(id_cols = HIK, names_from = YEAR, values_from = c("RACE", "BIRTHYR", "INCWAGE", "STATEFIP", "COUNTYICP")) |>
  filter(RACE_1940 %in% c(4,5)) |>
  mutate(
    in_sample = ifelse(BIRTHYR_1940 < 1926, "old enough", "too young")
  )

workingage_sample <- j_c_sample |>
  filter(in_sample == "old enough")

j_c_sample |>
  count(in_sample) |>
  mutate(percent = round((n / sum(n))*100))
#+end_src

#+RESULTS:
| in_sample  |     n | percent |
|------------+-------+---------|
| too young  | 24300 |      33 |
| old enough | 49512 |      67 |

Now for the subsample of MLP respondents who are reported as Japanese or Chinese in 1940,
how many of them consistently report a wage in both years,
as well as a state and county across both years?
#+begin_src R
tar_load(wage_sample)

wage_sample |>
  count(race_adj)
#+end_src

#+RESULTS:
| Chinese  | 2069 |
| Japanese | 6067 |

So there should be 8,136 observations in my main analysis sample.

** Descriptive Patterns

#+begin_src R :results graphics file :file figures/INCWAGE_plot.pdf
wage_sample |>
  filter(
    int_prob == 0 | int_prob > 0.5
    ) |>
  pivot_longer(
    cols = INCWAGE_1940:INCWAGE_1950,
    values_to = "INCWAGE",
    names_to = "YEAR"
  ) |>
  ggplot(
    aes(x = YEAR, y = INCWAGE, color = int_prob)
  ) +
  geom_point() +
  facet_wrap(~ as_factor(race_adj) + as_factor(sex_adj)) +
  geom_smooth(method = "lm") +
  scale_y_log10() +
  labs(
    x = "Internment Status",
    fill = "Internment Status",
    y = "% change in income 1940-1950"
  ) +
  theme_internment() +
  theme(legend.position = "bottom")
#+end_src

#+RESULTS:
[[file:figures/INCWAGE_plot.pdf]]

** Summary Statistics
#+begin_src R 
table_dt <- wage_sample |>
  mutate(
    employed_1940 = as_factor(employed_1940),
    employed_1950 = as_factor(employed_1950),
    migrant = as_factor(migrate10),
    FARM_1940 = ifelse(FARM_1940 == "Farm", 1, 0),
    FARM_1950 = ifelse(FARM_1950 == "Farm", 1, 0),
    Female = ifelse(sex_adj=="Female", 1, 0),
    employed_1940 = as.numeric(employed_1940),
    employed_1950 = as.numeric(employed_1950),
    migrant = as.numeric(migrant)
  ) |>
  select(`Race` = race_adj,
         ## `Internment probability` = int_prob,
         `Year of birth` = birthyr_adj,
         Female,
         `Farm status 1940`=FARM_1940,
         `Farm status 1950`=FARM_1950,
         `Wage income 1939`=INCWAGE_1940, `Wage income 1949`=INCWAGE_1950, 
         `Business/farm income 1949`=INCBUSFM_1950, `Other income 1949`=INCOTHER_1950,
         `OCCSCORE 1940`=OCCSCORE_1940, `OCCSCORE in 1950`=OCCSCORE_1950,
         `Weeks worked in 1939`=WKSWORK1_1940, `Weeks worked in 1949`=WKSWORK1_1950,
         `Hours worked last week (1940)`=HRSWORK1_1940, `Hours worked last week (1950)`=HRSWORK1_1950,
         `Was employed 1940`=employed_1940, `Was employed 1950`=employed_1950,
         `Moved counties 1940-1950`=migrant) 

modelsummary::datasummary_balance(~Race, table_dt)
#+end_src

#+RESULTS:

#+begin_src R :results output file :file tables/mlp_sumstats.tex
modelsummary::datasummary_balance(
                ~Race, table_dt,
                output = "latex" 
#+end_src

#+RESULTS:
[[file:tables/mlp_sumstats.tex]]

** Regressions
*** Relationship between internment status and 1950 salary

#+begin_src R :session *R:internment*  :results output file :file tables/reg1_tbl.tex
etable(
  feols(
    INCWAGE_1950 ~ int_prob,
    data = wage_sample
  ),
  feols(
    INCWAGE_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj ,
    data = wage_sample
  ),
  feols(
    INCWAGE_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | EDUCD_1950,
    vcov = "IID",
    data = wage_sample
  ),
  feols(
    INCWAGE_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | EDUCD_1950 + STATEFIP_1940,
    cluster = ~STATEFIP_1940,
    data = wage_sample
  ),
  se.below = TRUE,
  dict = etable_dict,
  keep = c("Internment Status", "Age", "Age square", "Male", "Japanese", "Income in 1940"),
  keepFactors = FALSE,
  ## highlight = "Internment Status",
  title = "Earning effects of internment",
  label = "tbl:reg1",
  tex = TRUE
)
#+end_src

#+RESULTS:
[[file:tables/reg1_tbl.tex]]

F-Test of the null hypothesis that 1940 incomes and 1950 education levels jointly have coefficients equal to zero:
#+begin_src R :colnames yes
reg_wageint <- INCWAGE_1950 ~ int_prob +
    age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 |
    EDUCD_1950 + STATEFIP_1950

wald(feols(reg_wageint, data = wage_sample),
     "INCWAGE_1940|EDUCD_1950", cluster = "STATEFIP_1950")
#+end_src

#+RESULTS:
|             stat |                   p | df1 |  df2 | vcov                      |
|------------------+---------------------+-----+------+---------------------------|
| 147.534201619195 | 1.1789224050631e-33 |   1 | 8062 | Clustered (STATEFIP_1950) |

*** Other specifications
#+begin_src R :results output file :file tables/reghet_tbl.tex
reg_wagehet <- INCWAGE_1950 ~ int_prob +
    age_adj_1950 + age_adj_1950^2 + INCWAGE_1940 |
    EDUCD_1950

etable(
  feols(reg_wagehet,
        data = wage_sample),
  feols(reg_wagehet,
        data = wage_sample |>
          filter(sex_adj == "Male")),
  feols(reg_wagehet,
        data = wage_sample |>
          filter(sex_adj == "Female")),
  feols(reg_wagehet,
        data = wage_sample |>
          filter(race_adj == "Japanese", sex_adj == "Male")),
  feols(reg_wagehet,
        data = wage_sample |>
          filter(race_adj == "Japanese", sex_adj == "Female")),
  se.below = TRUE,
  ## vcov = "hetero",
  cluster = ~STATEFIP_1940,
  dict = etable_dict,
  keep = c("Internment Status", "Age", "Age square", "Male", "Japanese", "Income in 1940"),
  keepFactors = FALSE,
  ## highlight = "Internment Status",
  style.tex = style.tex("aer"),
  headers = c("All", "Male", "Female", "JM", "JF"),
  title = "Internment income effect heterogeneities",
  label = "tbl:reghet",
  notes = "This table reports the estimates of internment status on 1950 wages across different subsamples of the main linked sample. Column (1) includes Japanese and Chinese men and women, column (2) includes only Japanese and Chinese men, column (3) includes only Japanese and Chinese women, and column (4) includes only Japanese men.",
  tex = TRUE
)
#+end_src

#+RESULTS:
[[file:tables/reghet_tbl.tex]]

**** Arellano-Bover DiD

#+begin_src R :results output file :file tables/regAB.tex
wage_sample_did <- wage_sample |>
  pivot_longer(
    cols = ends_with(c("_1940","_1950")),
    names_pattern = "(.*)_(.*)",
    names_to = c(".value", "YEAR")
  ) |>
  mutate(YEAR = as_factor(YEAR))

AB_formula <- INCWAGE ~ YEAR + intprob_Ab + YEAR:intprob_AB + age_adj + age_adj^2 | EDUCD

etable(
  feols(
     INCWAGE ~ YEAR:int_prob + age_adj + age_adj^2 | EDUCD,
    data = wage_sample_did
  ),
  feols(
     INCWAGE ~ YEAR:intprob_AB + age_adj + age_adj^2 | EDUCD,
    data = wage_sample_did
  ),
  feols(
    INCWAGE ~ YEAR:intprob_full + age_adj + age_adj^2 | EDUCD + STATEFIP + COUNTYICP,
    data = wage_sample_did
  ),
  se.below = TRUE,
  tex = TRUE,
  adjustbox = TRUE,
  cluster = "COUNTYICP",
  dict = etable_dict,
  keepFactors = FALSE,
  title = "Difference-in-difference regression estimates",
  label = "tbl:regdid"
  ## notes = ""
)

#+end_src

#+RESULTS:
[[file:tables/regAB.tex]]

*** Alternative Internment statuses

#+begin_src R
data <- wage_sample |>
  mutate(
    state = as_factor(STATEFIP_1940),
    county = as_factor(STATEFIP_1940 * 10000 + COUNTYICP_1940),
    race = race_adj,
    sex = sex_adj
  )

Z <- c("state", "county", "sex", "race", "bpl_grp", "byr_grp")

c(combn(Z, 2), combn(Z,3))
#+end_src

#+RESULTS:
| state   |
| county  |
| state   |
| sex     |
| state   |
| race    |
| state   |
| bpl_grp |
| state   |
| byr_grp |
| county  |
| sex     |
| county  |
| race    |
| county  |
| bpl_grp |
| county  |
| byr_grp |
| sex     |
| race    |
| sex     |
| bpl_grp |
| sex     |
| byr_grp |
| race    |
| bpl_grp |
| race    |
| byr_grp |
| bpl_grp |
| byr_grp |
| state   |
| county  |
| sex     |
| state   |
| county  |
| race    |
| state   |
| county  |
| bpl_grp |
| state   |
| county  |
| byr_grp |
| state   |
| sex     |
| race    |
| state   |
| sex     |
| bpl_grp |
| state   |
| sex     |
| byr_grp |
| state   |
| race    |
| bpl_grp |
| state   |
| race    |
| byr_grp |
| state   |
| bpl_grp |
| byr_grp |
| county  |
| sex     |
| race    |
| county  |
| sex     |
| bpl_grp |
| county  |
| sex     |
| byr_grp |
| county  |
| race    |
| bpl_grp |
| county  |
| race    |
| byr_grp |
| county  |
| bpl_grp |
| byr_grp |
| sex     |
| race    |
| bpl_grp |
| sex     |
| race    |
| byr_grp |
| sex     |
| bpl_grp |
| byr_grp |
| race    |
| bpl_grp |
| byr_grp |

#+begin_src R :results output file :file tables/reg_altint.tex
etable(
  feols(
    INCWAGE_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | EDUCD_1950,
    vcov = "IID",
    data = wage_sample
  ),
  feols(
    INCWAGE_1950 ~ county_intprop + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | EDUCD_1950,
    vcov = "IID",
    data = wage_sample
  ),
  feols(
    INCWAGE_1950 ~ intprob_AB + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | EDUCD_1950,
    vcov = "IID",
    data = wage_sample
  ),
  feols(
    INCWAGE_1950 ~ intprob_full + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | EDUCD_1950,
    vcov = "IID",
    data = wage_sample
  ),
  tex = TRUE,
  se.below = TRUE,
  dict = etable_dict,
  keepFactors = FALSE,
  title = "Estimated effects using alternate internment prediction methods",
  label = "tbl:reg_altint"
)
#+end_src

#+RESULTS:
[[file:tables/reg_altint.tex]]

** Other outcomes

#+begin_src R :results output file :file tables/reg2_tbl.tex
etable(
  feglm(employed_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj ,
    data = wage_sample |> 
      mutate(employed_1950 = as.numeric(as.character(employed_1950))),
    family = binomial(link = "logit")
  ),
  feols(HRSWORK1_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + HRSWORK1_1940,
    data = wage_sample
  ),
  feols(WKSWORK1_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + WKSWORK1_1940,
    data = wage_sample
  ),
  feols(OCCSCORE_1950 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + OCCSCORE_1940,
    data = wage_sample
  ),
  feglm(change_occ ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj,
    data = wage_sample |>
      mutate(change_occ = (OCC1950_1950 == OCC1950_1940)),
    family = binomial(link = "logit")
  ),
  cluster = "STATEFIP_1940",
  se.below = TRUE,
  ## keep = c("Internment Status", "Age", "Age square", "Male", "Japanese", "Income in 1940"),
  dict = etable_dict,
  keepFactors = FALSE,
  title = "Employment and occupation effects",
  ## highlight = "Internment Status",
  label = "tbl:reg2",
  ## postprocess.tex = set_rules,
  tex = TRUE,
  adjustbox = TRUE
)
#+end_src

#+RESULTS:
[[file:tables/reg2_tbl.tex]]

#+begin_src R :results output file :file tables/reg3_tbl.tex
table_data <- wage_sample |>
  mutate(
    ctsal_1950 = county_med.salary_1950,
    ctsal_1940 = county_med.salary_1940,
    lnctsal_1950 = log(county_med.salary_1950),
    lnctsal_1940 = log(county_med.salary_1940),
    lnpop_1940 = log(county_pop_1940),
    ctpctjpn_1950 = county_pop.japanese_1950/county_pop_1950,
    ctpctjpn_1940 = county_pop.japanese_1940/county_pop_1940
  ) |>
  filter(
    !is.na(migrate10),
    !is.na(lnctsal_1950),
    !is.na(county_pop_1950),
    !is.na(ctpctjpn_1950)
  )
         
etable(
  feglm(
    migrate10 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940,
    data = table_data,
    family = binomial(link = "logit")
  ),
  feols(
    lnctsal_1940 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940,
    data = table_data |>
      filter(migrate10==1)
  ),
  feols(
   lnpop_1940 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940,
    data = table_data |>
      filter(migrate10==1)
  ),
  feols(
   ctpctjpn_1940 ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940,
    data = table_data |>
      filter(migrate10==1)
  ),
  cluster = "STATEFIP_1950",
  se.below = TRUE,
  keep = c("Internment Status", "Age", "Age square", "Male", "Japanese", "Income in 1940"),
  dict = c(
    "reset", # to reset global dict 
    migrate10="Migration", # as.numeric(employed_1950)="employment",
    lnctsal_1940="Log county income",
    county_pop_1950="County pop.",
    county_pop_1940="County pop.",
    lnpop_1940="Log county pop.",
    ctpctjpn_1950="County pct. Japn.",
    ctpctjpn_1940="County pct. Japn.",
    int_prob="Internment Status", age_adj_1950="Age", 
    sex_adjMale="Male", race_adjJapanese="Japanese", INCWAGE_1940="Income in 1940",
    EDUCD_1950="Education", STATEFIP_1950="State"
  ),
  keepFactors = FALSE,
  title = "Migration effects",
  label = "tbl:reg3",
  adjustbox = TRUE,
  tex = TRUE
)
#+end_src

#+RESULTS:
[[file:tables/reg3_tbl.tex]]

** Logit model of migration indicator
#+begin_src R  :results output
mig_logit <- glm(migrate10 ~ int_prob + AGE_1950 + AGE_1950^2,
    data = wage_sample, family = "binomial")
modelsummary::modelsummary(mig_logit)
#+end_src

#+RESULTS:
#+begin_example

+-----------------+-----------+
|                 | (1)       |
+=================+===========+
| (Intercept)     | -0.788    |
+-----------------+-----------+
|                 | (0.090)   |
+-----------------+-----------+
| int_prob | 0.793     |
+-----------------+-----------+
|                 | (0.057)   |
+-----------------+-----------+
| AGE_1950        | -0.013    |
+-----------------+-----------+
|                 | (0.002)   |
+-----------------+-----------+
| Num.Obs.        | 8136      |
+-----------------+-----------+
| AIC             | 9750.1    |
+-----------------+-----------+
| BIC             | 9771.1    |
+-----------------+-----------+
| Log.Lik.        | -4872.031 |
+-----------------+-----------+
| F               | 123.705   |
+-----------------+-----------+
| RMSE            | 0.45      |
+-----------------+-----------+
#+end_example

** County characteristics as outcome
#+begin_src R 
etable(feols(
  c(county_med.salary_1950, county_pop_1950, county_pop.japanese_1950/county_pop_1950) ~
    int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | STATEFIP_1950,
  cluster = ~STATEFIP_1950,
  data = wage_sample)
  )
#+end_src

#+RESULTS:
|                     | feols(c(county_med...1 | feols(c(county_med...2 | feols(c(county_med.salary_1950, count..3 |
|---------------------+------------------------+------------------------+------------------------------------------|
| Dependent Var.:     | county_med.salary_1950 | county_pop_1950        | county_pop.japanese_1950/county_pop_1950 |
|                     |                        |                        |                                          |
| int_prob     | -21.81 (55.63)         | -427,639.0 (479,833.5) | 0.0057 (0.0043)                          |
| age_adj_1950        | -2.216. (1.162)        | 8,709.7** (3,104.1)    | -3.91e-5* (1.75e-5)                      |
| age_adj_1950 square | 0.0197 (0.0118)        | -117.2** (38.66)       | 5.64e-7* (2.13e-7)                       |
| sex_adjMale             | -13.03* (5.287)        | -7,896.9 (8,410.9)     | 0.0002* (9.33e-5)                        |
| race_adjJapanese        | -140.9*** (35.73)      | 824,057.7 (584,045.5)  | -0.0017 (0.0035)                         |
| INCWAGE_1940        | 0.0149*** (0.0020)     | 15.85*** (4.459)       | -3.1e-7*** (8.61e-8)                     |
| Fixed-Effects:      | ---------------------- | ---------------------- | ------------------------------           |
| STATEFIP_1950       | Yes                    | Yes                    | Yes                                      |
| ___________________   | ______________________   | ______________________   | ______________________________             |
| S.E.: Clustered     | by: STATEFIP_1950      | by: STATEFIP_1950      | by: STATEFIP_1950                        |
| Observations        | 8,109                  | 8,109                  | 8,109                                    |
| R2                  | 0.37151                | 0.40159                | 0.38425                                  |
| Within R2           | 0.1453                 | 0.04175                | 0.0456                                   |

** Occupations
#+begin_src R 
etable(feols(
  as.numeric(employed_1950) ~ int_prob + age_adj_1950 + age_adj_1950^2 + sex_adj + race_adj + INCWAGE_1940 | STATEFIP_1950,
  data =  wage_sample)
  )
#+end_src

#+RESULTS:
|                     | feols(as.numeric(employ.. |
|---------------------+---------------------------|
| Dependent Var.:     | as.numeric(employed_1950) |
|                     |                           |
| int_prob     | -0.0076 (0.0135)          |
| age_adj_1950        | 0.0270*** (0.0027)        |
| age_adj_1950 square | -0.0004*** (2.82e-5)      |
| SEXMale             | 0.4163*** (0.0132)        |
| race_adjJapanese        | 0.0895*** (0.0174)        |
| INCWAGE_1940        | 2.49e-5*** (4.97e-6)      |
| Fixed-Effects:      | ------------------------- |
| STATEFIP_1950       | Yes                       |
| ___________________   | _________________________   |
| S.E.: Clustered     | by: STATEFIP_1950         |
| Observations        | 8,136                     |
| R2                  | 0.2582                    |
| Within R2           | 0.2509                    |


For those who had listed occupations in 1940 and 1950,
and for which their occupation changed,
here is the breakdown of the most common occupation changes:
#+begin_src R :colnames yes
mlp_cleaned |>
  filter(OCC1950 != "N/A (blank)") |>
  pivot_wider(id_cols = "id", names_from = YEAR, values_from = OCC1950, names_prefix = "OCC_") |>
  count(OCC_1940, OCC_1950) |>
  filter(
    !is.na(OCC_1940),
    !is.na(OCC_1950),
    OCC_1940 != OCC_1950
    ) |>
  arrange(desc(n)) |>
  head(n=25)
    #+end_src

#+RESULTS:
| OCC_1940                                   | OCC_1950                                   |   n |
|--------------------------------------------+--------------------------------------------+-----|
| Farmers (owners and tenants)               | Farm laborers, wage workers                | 594 |
| Farm laborers, unpaid family workers       | Farmers (owners and tenants)               | 486 |
| Farm laborers, wage workers                | Farmers (owners and tenants)               | 481 |
| Salesmen and sales clerks (nec)            | Managers, officials, and proprietors (nec) | 350 |
| Farm laborers, unpaid family workers       | Farm laborers, wage workers                | 265 |
| Farmers (owners and tenants)               | Gardeners, except farm and groundskeepers  | 249 |
| Managers, officials, and proprietors (nec) | Salesmen and sales clerks (nec)            | 234 |
| Managers, officials, and proprietors (nec) | Not yet classified                         | 232 |
| Farmers (owners and tenants)               | Farm laborers, unpaid family workers       | 222 |
| Farmers (owners and tenants)               | Not yet classified                         | 194 |
| Salesmen and sales clerks (nec)            | Operative and kindred workers (nec)        | 170 |
| Managers, officials, and proprietors (nec) | Gardeners, except farm and groundskeepers  | 165 |
| Laundry and dry cleaning Operatives        | Managers, officials, and proprietors (nec) | 164 |
| Salesmen and sales clerks (nec)            | Not yet classified                         | 163 |
| Managers, officials, and proprietors (nec) | Cooks, except private household            | 158 |
| Managers, officials, and proprietors (nec) | Farmers (owners and tenants)               | 149 |
| Farm laborers, wage workers                | Gardeners, except farm and groundskeepers  | 144 |
| Cooks, except private household            | Managers, officials, and proprietors (nec) | 139 |
| Farmers (owners and tenants)               | Managers, officials, and proprietors (nec) | 134 |
| Waiters and waitresses                     | Managers, officials, and proprietors (nec) | 126 |
| Gardeners, except farm and groundskeepers  | Farmers (owners and tenants)               | 126 |
| Farm laborers, wage workers                | Not yet classified                         | 124 |
| Managers, officials, and proprietors (nec) | Operative and kindred workers (nec)        | 123 |
| Farm laborers, unpaid family workers       | Operative and kindred workers (nec)        | 121 |
| Farm laborers, unpaid family workers       | Not yet classified                         | 109 |

In the main analysis sample:
#+begin_src R :colnames yes
wage_sample |>
  filter(
    !is.na(OCC1950_1940),
    !is.na(OCC1950_1950),
    OCC1950_1940 != "N/A (blank)",
    ! OCC1950_1950 %in% c("N/A (blank)", "Not yet classified"),
    int_prob > 0.5
  ) |>
  group_by(OCC1950_1940, OCC1950_1950) |>
  summarise(n = n()) |>
  ungroup() |>
  mutate(p = round(n / sum(n), 2)) |>
  arrange(desc(n)) |>
  head(25)
#+end_src

#+RESULTS:
| OCC1950_1940                               | OCC1950_1950                               |   n |    p |
|--------------------------------------------+--------------------------------------------+-----+------|
| Farmers (owners and tenants)               | Farmers (owners and tenants)               | 169 | 0.07 |
| Farm laborers, wage workers                | Farm laborers, wage workers                |  94 | 0.04 |
| Managers, officials, and proprietors (nec) | Managers, officials, and proprietors (nec) |  88 | 0.04 |
| Farm laborers, wage workers                | Farmers (owners and tenants)               |  80 | 0.03 |
| Farmers (owners and tenants)               | Farm laborers, wage workers                |  78 | 0.03 |
| Gardeners, except farm and groundskeepers  | Gardeners, except farm and groundskeepers  |  77 | 0.03 |
| Farm laborers, unpaid family workers       | Farmers (owners and tenants)               |  60 | 0.02 |
| Farmers (owners and tenants)               | Gardeners, except farm and groundskeepers  |  48 | 0.02 |
| Salesmen and sales clerks (nec)            | Salesmen and sales clerks (nec)            |  44 | 0.02 |
| Farmers (owners and tenants)               | Farm laborers, unpaid family workers       |  39 | 0.02 |
| Farm laborers, unpaid family workers       | Farm laborers, wage workers                |  39 | 0.02 |
| Private household workers (nec)            | Private household workers (nec)            |  34 | 0.01 |
| Managers, officials, and proprietors (nec) | Salesmen and sales clerks (nec)            |  33 | 0.01 |
| Farm laborers, unpaid family workers       | Farm laborers, unpaid family workers       |  30 | 0.01 |
| Salesmen and sales clerks (nec)            | Operative and kindred workers (nec)        |  29 | 0.01 |
| Salesmen and sales clerks (nec)            | Managers, officials, and proprietors (nec) |  28 | 0.01 |
| Farm laborers, unpaid family workers       | Operative and kindred workers (nec)        |  27 | 0.01 |
| Managers, officials, and proprietors (nec) | Gardeners, except farm and groundskeepers  |  26 | 0.01 |
| Gardeners, except farm and groundskeepers  | Farmers (owners and tenants)               |  26 | 0.01 |
| Farm laborers, wage workers                | Farm laborers, unpaid family workers       |  24 | 0.01 |
| Farm laborers, wage workers                | Gardeners, except farm and groundskeepers  |  23 | 0.01 |
| Managers, officials, and proprietors (nec) | Farmers (owners and tenants)               |  20 | 0.01 |
| Managers, officials, and proprietors (nec) | Operative and kindred workers (nec)        |  20 | 0.01 |
| Operative and kindred workers (nec)        | Operative and kindred workers (nec)        |  20 | 0.01 |
| Salesmen and sales clerks (nec)            | Gardeners, except farm and groundskeepers  |  19 | 0.01 |

** Were internees moving out of the West Coast?
#+begin_src R 
mlp_sample |>
  select(YEAR, STATEFIP, COUNTYICP, race_adj, id) |>
  pivot_wider(id_cols = c("race_adj", "id"), names_from = YEAR, values_from = c("STATEFIP","COUNTYICP"), names_sep = "_") |>
  filter(COUNTYICP_1940 != COUNTYICP_1950) |>
  mutate(
    WC_1940 = ifelse(STATEFIP_1940 %in% c(4,6,41,53), "West Coast", "Other"),
    WC_1950 = ifelse(STATEFIP_1950 %in% c(4,6,41,53), "West Coast", "Other"),
    ) |>
  count(race_adj, WC_1940, WC_1950) |>
  arrange(race_adj, desc(n)) |>
  pivot_wider(names_from = c("WC_1940", "WC_1950"), values_from = n)
#+end_src

#+RESULTS:
| Chinese  | 1195 | 785 | 259 |  201 |
| Japanese | 6326 | 839 | 223 | 5472 |

*** State Migrations
#+begin_src R 
mlp_sample |>
  count(STATEFIP,YEAR) |>
  pivot_wider(names_from = YEAR, values_from = n, names_prefix = "N_") |>
  mutate(
    pct_of_1940 = N_1950/N_1940,
    state = as_factor(STATEFIP)
  ) |>
  print(n=52)
#+end_src

#+RESULTS:
| STATEFIP | N_1940 | N_1950 |       pct_of_1940 | state                |
|----------+--------+--------+-------------------+----------------------|
|        1 |     35 |     33 | 0.942857142857143 | Alabama              |
|        2 |        |      3 |                   | Alaska               |
|        4 |    440 |    447 |  1.01590909090909 | Arizona              |
|        5 |     56 |     59 |  1.05357142857143 | Arkansas             |
|        6 |  34156 |  30355 | 0.888716477339267 | California           |
|        8 |    923 |   1430 |  1.54929577464789 | Colorado             |
|        9 |     51 |     63 |  1.23529411764706 | Connecticut          |
|       10 |     16 |     15 |            0.9375 | Delaware             |
|       11 |    107 |    182 |  1.70093457943925 | District of Columbia |
|       12 |     75 |     94 |  1.25333333333333 | Florida              |
|       13 |     71 |     68 | 0.957746478873239 | Georgia              |
|       15 |        |    284 |                   | Hawaii               |
|       16 |    407 |    608 |  1.49385749385749 | Idaho                |
|       17 |    426 |   2588 |  6.07511737089202 | Illinois             |
|       18 |     44 |     57 |  1.29545454545455 | Indiana              |
|       19 |     20 |     33 |              1.65 | Iowa                 |
|       20 |     26 |     29 |  1.11538461538462 | Kansas               |
|       21 |     20 |     18 |               0.9 | Kentucky             |
|       22 |     81 |     89 |  1.09876543209877 | Louisiana            |
|       23 |     14 |      8 | 0.571428571428571 | Maine                |
|       24 |     74 |    106 |  1.43243243243243 | Maryland             |
|       25 |    374 |    392 |  1.04812834224599 | Massachusetts        |
|       26 |    202 |    433 |  2.14356435643564 | Michigan             |
|       27 |    119 |    305 |  2.56302521008403 | Minnesota            |
|       28 |    119 |     92 | 0.773109243697479 | Mississippi          |
|       29 |     69 |    120 |  1.73913043478261 | Missouri             |
|       30 |    150 |    146 | 0.973333333333333 | Montana              |
|       31 |    171 |    194 |  1.13450292397661 | Nebraska             |
|       32 |    143 |    128 | 0.895104895104895 | Nevada               |
|       33 |      5 |      5 |                 1 | New Hampshire        |
|       34 |    220 |    522 |  2.37272727272727 | New Jersey           |
|       35 |     60 |     70 |  1.16666666666667 | New Mexico           |
|       36 |   1939 |   2118 |  1.09231562661166 | New York             |
|       37 |     41 |     42 |  1.02439024390244 | North Carolina       |
|       38 |     32 |     25 |           0.78125 | North Dakota         |
|       39 |    197 |    555 |  2.81725888324873 | Ohio                 |
|       40 |     42 |     35 | 0.833333333333333 | Oklahoma             |
|       41 |   1900 |   1657 | 0.872105263157895 | Oregon               |
|       42 |    246 |    346 |  1.40650406504065 | Pennsylvania         |
|       44 |     50 |     49 |              0.98 | Rhode Island         |
|       45 |     27 |     26 | 0.962962962962963 | South Carolina       |
|       46 |     15 |     12 |               0.8 | South Dakota         |
|       47 |     24 |     29 |  1.20833333333333 | Tennessee            |
|       48 |    287 |    353 |  1.22996515679443 | Texas                |
|       49 |    719 |   1109 |  1.54242002781641 | Utah                 |
|       50 |        |      2 |                   | Vermont              |
|       51 |     35 |     52 |  1.48571428571429 | Virginia             |
|       53 |   5054 |   3709 | 0.733874159081915 | Washington           |
|       54 |     12 |      7 | 0.583333333333333 | West Virginia        |
|       55 |     48 |    115 |  2.39583333333333 | Wisconsin            |
|       56 |    170 |    131 | 0.770588235294118 | Wyoming              |
|          |    337 |    501 |    1.486646884273 |                      |

*** County Migrations
#+begin_src R 

#+end_src
