#+TITLE: Internee Outcomes: Data Analysis
#+PROPERTY: header-args:R: :session *R:internment* :export both

#+begin_src R :results silent :session *R:internment*
library(tidyverse)
library(duckdb)
library(haven)
library(fixest)
library(ggplot2)

library(targets)

tar_load(c(sample_long))
#+end_src

* MLP Linked Internees
:PROPERTIES:
:header-args:R: :session *R:internment*
:END:
** Linked Sample Size
I want to focus on the Japanese and Chinese populations as the main treatment and control groups of my study.
However, it's not as simple as just filtering on race status in one reference year.
There are many linked individuals who report different racial categories across the different census years.
This may be due to transcription errors, differences in census takers, false matches in the MLP linking process, etc.

#+begin_src R
tbl(con, mlp_tbl) |>
  count(YEAR, RACE) |>
  collect() |>
  ipumsr::set_ipums_var_attributes(var_info = ipumsr::read_ipums_ddi(ddi_mlp)) |>
  mutate(RACE = as_factor(RACE)) |>
  pivot_wider(names_from = RACE, values_from = n)
#+end_src

#+RESULTS:
| YEAR |    White | Black/African American | American Indian or Alaska Native | Chinese | Japanese | Other Asian or Pacific Islander | Other race, nec |
|------+----------+------------------------+----------------------------------+---------+----------+---------------------------------+-----------------|
| 1940 | 68426104 |                5006313 |                           144394 |   20882 |    52930 |                           13855 |             237 |
| 1950 | 68444757 |                5052709 |                           110224 |   13146 |    35008 |                            7797 |            1074 |

Notice how almost all of the individuals who are reported as White are consistently White across years,
but the number of linked individuals who are Chinese or Japanese decrease significantly in 1950.
This may be because the 1950 full-count census data are more recent and still being worked on,
so for now it's probably safest to use the 1940 =RACE= status to assign race in my study.

Based on this, there are 73,812 linked individuals who report being either Japanese or Chinese in 1940
(and potentially some other race in 1950).


The match rate for this population is a little less than the ~55% match rate in the MLP linkages overall.
Based on the numbers in the table above, the match rate for Japanese/Chinese respondents is 73,812 / 204,906 ≈ 36%.

| Source:  | Year | Total   | Japanese | Chinese | Japanese + Chinese |
|----------+------+---------+----------+---------+--------------------|
| Census   | 1940 | 132.9 m |   126701 |   78205 |             204906 |
|          | 1950 | 152.3 m |   278603 |  119522 |             398125 |
|----------+------+---------+----------+---------+--------------------|
| MLP v2.0 | 1940 | 73.7 m  |    52930 |   20882 |              73812 |
|          | 1950 | 73.7 m  |    35008 |   13146 |              48154 |

For my main analysis on the growth of incomes among this group,
I select only those individuals who would have been of working age in 1940 and thus able to have worked a job in both years observed.
This means that I filter the MLP sample for anyone born before 1926.
Someone born in January of 1926 would have been 13 in the year 1939
making them too young to be asked about their earnings or employment when surveyed in 1940.
#+begin_src R
j_c_sample <- tbl(con, mlp_tbl) |>
  pivot_wider(id_cols = HIK, names_from = YEAR, values_from = c("RACE", "BIRTHYR", "INCWAGE", "STATEFIP", "COUNTYICP")) |>
  filter(RACE_1940 %in% c(4,5)) |>
  mutate(
    in_sample = ifelse(BIRTHYR_1940 < 1926, "old enough", "too young")
  )

workingage_sample <- j_c_sample |>
  filter(in_sample == "old enough")

j_c_sample |>
  count(in_sample) |>
  mutate(percent = round((n / sum(n))*100))
#+end_src

#+RESULTS:
| in_sample  |     n | percent |
|------------+-------+---------|
| too young  | 24300 |      33 |
| old enough | 49512 |      67 |

Now for the subsample of MLP respondents who are reported as Japanese or Chinese in 1940,
how many of them consistently report a wage in both years,
as well as a state and county across both years?
#+begin_src R
wage_sample <- workingage_sample |>
  filter(
    !INCWAGE_1940 %in% c(999999, 999998),
    !INCWAGE_1950 %in% c(999999,999998),
    !is.na(STATEFIP_1940),
    !is.na(COUNTYICP_1940),
    !is.na(STATEFIP_1950),
    !is.na(COUNTYICP_1950)
  )

wage_sample |>
  count(RACE_1940)
#+end_src

#+RESULTS:
| RACE_1940 |    n |
|-----------+------|
|         4 | 2470 |
|         5 | 6610 |

So there should be 9,080 observations in my main analysis sample.

** Descriptive Patterns

#+begin_src R :results graphics file :file figures/INCWAGE_plot.pdf
ggplot(
  aes(x = internment_prob, y = Earning_growth, color = internment_prob),
  data = sample_long
) +
  geom_point() +
  ## facet_wrap(~ as_factor(RACE_1940) + as_factor(SEX_1950)) +
  geom_smooth(method = "lm") +
  scale_y_log10() +
  theme_internment()
#+end_src

#+RESULTS:
[[file:figures/INCWAGE_plot.pdf]]

** Summary Statistics
#+begin_src R :colnames yes
linked_data_full |> 
  group_by(race, YEAR) |>
  summarise(
    n = n(),
    across(c(salary, SEX, OCCSCORE, age, employed, WKSWORK1),
           ~round(mean(., na.rm=T), digits = 2)
           )
  )
#+end_src

#+RESULTS:
| race     | YEAR |    n | salary |  SEX | OCCSCORE |   age | employed | WKSWORK1 |
|----------+------+------+--------+------+----------+-------+----------+----------|
| Chinese  | 1940 | 6448 |  589.5 | 1.33 |    10.42 | 26.99 |     0.37 |    17.88 |
| Chinese  | 1950 | 6448 | 886.18 | 1.34 |     12.9 | 36.99 |      0.5 |      6.3 |
| Japanese | 1940 | 4631 | 390.66 | 1.45 |        8 |  32.2 |     0.42 |    19.84 |
| Japanese | 1950 | 4631 | 889.03 | 1.45 |     8.74 |  42.2 |     0.52 |     7.75 |

#+begin_src R :exports both :results output
table_dt <- sampleline_sample |>
  select(race, salary_1940, salary_1950,
         employed_1940, employed_1950, income_tot, OCCSCORE_1940, OCCSCORE_1950, WKSWORK1_1940, WKSWORK1_1950, employed_1940, employed_1950, age_1950, migrate10, sex) 
modelsummary::datasummary_balance(~race, table_dt)
#+end_src

#+RESULTS:
#+begin_example
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
|                        | Chinese (N=555)    | Japanese (N=360)   |                             |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
|               |        | Mean   | Std. Dev. | Mean   | Std. Dev. | Diff. in Means | Std. Error |
+===============+========+========+===========+========+===========+================+============+
| salary_1940   |        | 1023.0 | 1264.5    | 569.9  | 1012.6    | -453.1         | 76.5       |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| salary_1950   |        | 1449.9 | 1689.8    | 1242.9 | 1547.6    | -207.0         | 109.9      |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| employed_1940 |        | 0.9    | 0.3       | 1.0    | 0.1       | 0.1            | 0.0        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| employed_1950 |        | 0.9    | 0.3       | 1.0    | 0.1       | 0.1            | 0.0        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| income_tot    |        | 2722.1 | 2255.8    | 2510.3 | 2349.1    | -211.9         | 159.8      |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| OCCSCORE_1940 |        | 25.2   | 13.0      | 16.7   | 11.6      | -8.4           | 0.8        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| OCCSCORE_1950 |        | 25.8   | 14.9      | 16.0   | 10.9      | -9.8           | 0.9        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| WKSWORK1_1940 |        | 42.7   | 16.8      | 44.4   | 14.7      | 1.7            | 1.1        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| WKSWORK1_1950 |        | 40.9   | 18.4      | 42.9   | 16.1      | 2.0            | 1.2        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| age_1950      |        | 47.6   | 9.9       | 49.6   | 13.7      | 2.0            | 0.8        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| migrate10     |        | 0.1    | 0.3       | 0.1    | 0.3       | 0.0            | 0.0        |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
|               |        | N      | Pct.      | N      | Pct.      |                |            |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
| sex           | Female | 33     | 5.9       | 55     | 15.3      |                |            |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
|               | Male   | 522    | 94.1      | 305    | 84.7      |                |            |
+---------------+--------+--------+-----------+--------+-----------+----------------+------------+
#+end_example

** Regressions
*** Relationship between internment status and 1950 salary
#+begin_src R :session *R:internment* :results silent
con <- dbConnect(duckdb(), mlp_db)

reg_data <- tbl(con, mlp_tbl) |>
  filter(
    !INCWAGE %in% c(999999,999998),
    !is.na(STATEFIP),
    !is.na(COUNTYICP),
    (BIRTHYR < 1926)
  ) |>
  pivot_wider(
    id_cols = HIK, names_from = YEAR,
    values_from = c("RACE", "BIRTHYR", "INCWAGE", "STATEFIP", "COUNTYICP", "AGE", "SEX",
                    "EDUCD", "WKSWORK1", "OCC1950", "OCCSCORE", "EMPSTAT")
  ) |>
  filter(RACE_1940 %in% c(4,5)) |>
  collect() |>
  filter(!is.na(INCWAGE_1950)) |>
  mutate(INCWAGE_1940 = INCWAGE_1940 * 1.69) |>
  mutate(Earning_growth = (INCWAGE_1950 - INCWAGE_1940) / INCWAGE_1940) |>
  left_join(
    internpr,
    by = c("RACE_1940"="RACE", "STATEFIP_1940"="STATEFIP", "COUNTYICP_1940"="COUNTYICP")
  ) 

head(reg_data)
#+end_src

#+RESULTS:

#+begin_src R :session *R:internment* :colnames yes
etable(
  feols(
    INCWAGE_1950 ~ internment_prob,
    data = reg_data
  ),
  feols(
    INCWAGE_1950 ~ internment_prob + AGE_1950 + AGE_1950^2 + as_factor(SEX_1940) + as_factor(RACE_1940),
    data = reg_data  
  ),
  feols(
    INCWAGE_1950 ~ internment_prob + AGE_1950 + AGE_1950^2 + as_factor(SEX_1940) + as_factor(RACE_1940) + as_factor(EDUCD_1950) + INCWAGE_1940,
    data = reg_data
  )
  )
#+end_src

#+RESULTS:
|                             | feols(INCWAGE_19.. | feols(INCWAGE_195.. | feols(INCWAGE_195.. |
|-----------------------------+--------------------+---------------------+---------------------|
| Dependent Var.:             | INCWAGE_1950       | INCWAGE_1950        | INCWAGE_1950        |
|                             |                    |                     |                     |
| Constant                    | 1,080.5*** (26.53) | 872.9*** (173.7)    | 915.1*** (198.3)    |
| internment_prob             | -43.38 (34.11)     | 207.4*** (56.94)    | 231.7*** (56.30)    |
| AGE_1950                    |                    | 31.76*** (7.481)    | 12.04 (7.813)       |
| AGE_1950 square             |                    | -0.5214*** (0.0772) | -0.3116*** (0.0795) |
| as_factor(SEX_1940)2        |                    | -643.9*** (32.03)   | -481.5*** (33.53)   |
| as_factor(RACE_1940)Chinese |                    | 190.4** (59.85)     | 220.6*** (60.15)    |
| as_factor(EDUCD_1950)2      |                    |                     | 114.0 (93.37)       |
| as_factor(EDUCD_1950)12     |                    |                     | 158.9 (198.1)       |
| as_factor(EDUCD_1950)14     |                    |                     | -10.76 (129.5)      |
| as_factor(EDUCD_1950)15     |                    |                     | -40.03 (131.4)      |
| as_factor(EDUCD_1950)16     |                    |                     | 280.1* (139.5)      |
| as_factor(EDUCD_1950)17     |                    |                     | 152.1 (113.8)       |
| as_factor(EDUCD_1950)22     |                    |                     | -2.612 (123.9)      |
| as_factor(EDUCD_1950)23     |                    |                     | 177.3. (107.2)      |
| as_factor(EDUCD_1950)25     |                    |                     | 73.26 (124.9)       |
| as_factor(EDUCD_1950)26     |                    |                     | 104.3 (89.10)       |
| as_factor(EDUCD_1950)30     |                    |                     | 160.6 (115.9)       |
| as_factor(EDUCD_1950)40     |                    |                     | 54.77 (108.2)       |
| as_factor(EDUCD_1950)50     |                    |                     | 179.0 (119.8)       |
| as_factor(EDUCD_1950)60     |                    |                     | 237.0** (85.02)     |
| as_factor(EDUCD_1950)70     |                    |                     | 343.2** (129.8)     |
| as_factor(EDUCD_1950)80     |                    |                     | 248.0* (115.2)      |
| as_factor(EDUCD_1950)90     |                    |                     | -12.85 (156.6)      |
| as_factor(EDUCD_1950)100    |                    |                     | 444.0*** (113.2)    |
| as_factor(EDUCD_1950)110    |                    |                     | 738.5*** (143.1)    |
| as_factor(EDUCD_1950)999    |                    |                     | 643.9 (644.1)       |
| INCWAGE_1940                |                    |                     | 0.2476*** (0.0180)  |
| ___________________________ | __________________ | ___________________ | ___________________ |
| S.E. type                   | IID                | IID                 | IID                 |
| Observations                | 8,992              | 8,992               | 8,992               |
| R2                          | 0.00018            | 0.07428             | 0.10159             |
| Adj. R2                     | 6.87e-05           | 0.07376             | 0.09898             |

#+begin_src R :session *R:internment* :colnames yes
etable(
  feols(
    INCWAGE_1950 ~ internment_prob + AGE_1950 + AGE_1950^2 + as_factor(RACE_1940) + as_factor(EDUCD_1950) + INCWAGE_1940,
    data = reg_data |> filter(SEX_1950==1)
  ),
  feols(
    INCWAGE_1950 ~ internment_prob + AGE_1950 + AGE_1950^2 + as_factor(RACE_1940) + as_factor(EDUCD_1950) + INCWAGE_1940,
    data = reg_data |> filter(SEX_1950==2)
  ),
  feols(
    INCWAGE_1950 ~ internment_prob + AGE_1950 + AGE_1950^2 + as_factor(SEX_1950) + as_factor(EDUCD_1950) + INCWAGE_1940,
    data = reg_data |> filter(RACE_1940==5)
  )
  )
#+end_src

#+RESULTS:
|                             | feols(INCWAGE_195.. | feols(INCWAGE_19.. | feols(INCWAGE_195.. |
|-----------------------------+---------------------+--------------------+---------------------|
| Dependent Var.:             | INCWAGE_1950        | INCWAGE_1950       | INCWAGE_1950        |
|                             |                     |                    |                     |
| Constant                    | 315.1 (270.3)       | 1,600.4*** (295.5) | 786.1*** (232.6)    |
| internment_prob             | 234.9** (77.92)     | 205.7** (77.70)    | 229.5*** (55.47)    |
| AGE_1950                    | 38.48*** (10.55)    | -39.03*** (11.76)  | 18.89* (9.268)      |
| AGE_1950 square             | -0.5787*** (0.1057) | 0.2363. (0.1244)   | -0.3732*** (0.0947) |
| as_factor(RACE_1940)Chinese | 276.6*** (81.50)    | 82.96 (86.44)      |                     |
| as_factor(EDUCD_1950)2      | 71.46 (130.7)       | 137.2 (126.8)      | 104.5 (119.7)       |
| as_factor(EDUCD_1950)12     | -78.58 (254.6)      | 733.8* (318.1)     | 385.0 (267.1)       |
| as_factor(EDUCD_1950)14     | -50.53 (177.2)      | 5.313 (181.9)      | -49.56 (157.6)      |
| as_factor(EDUCD_1950)15     | -29.73 (173.9)      | -102.1 (197.6)     | -96.85 (179.2)      |
| as_factor(EDUCD_1950)16     | 364.4. (189.7)      | 73.64 (197.9)      | 228.8 (191.1)       |
| as_factor(EDUCD_1950)17     | 209.5 (158.8)       | 51.91 (154.5)      | 101.6 (140.4)       |
| as_factor(EDUCD_1950)22     | -24.74 (169.3)      | -7.884 (174.1)     | 83.22 (157.4)       |
| as_factor(EDUCD_1950)23     | 187.0 (151.6)       | 136.3 (143.5)      | 176.6 (130.5)       |
| as_factor(EDUCD_1950)25     | 98.48 (169.9)       | -5.717 (177.1)     | -25.77 (158.5)      |
| as_factor(EDUCD_1950)26     | 63.82 (124.8)       | 134.9 (120.7)      | 70.29 (107.5)       |
| as_factor(EDUCD_1950)30     | 372.4* (162.2)      | -149.6 (156.7)     | 199.0 (136.9)       |
| as_factor(EDUCD_1950)40     | 93.71 (150.2)       | 4.718 (148.1)      | 47.12 (128.5)       |
| as_factor(EDUCD_1950)50     | 257.2 (165.0)       | 49.39 (166.1)      | 109.5 (141.0)       |
| as_factor(EDUCD_1950)60     | 291.4* (118.2)      | 152.3 (116.3)      | 198.5. (102.9)      |
| as_factor(EDUCD_1950)70     | 416.5* (174.9)      | 180.4 (187.5)      | 500.5** (152.7)     |
| as_factor(EDUCD_1950)80     | 287.9. (155.5)      | 177.5 (166.2)      | 283.6* (136.9)      |
| as_factor(EDUCD_1950)90     | -54.20 (196.1)      | 271.6 (285.1)      | 28.93 (187.2)       |
| as_factor(EDUCD_1950)100    | 324.6* (149.1)      | 794.3*** (175.5)   | 328.8* (133.6)      |
| as_factor(EDUCD_1950)110    | 679.9*** (178.7)    | 1,012.7*** (270.3) | 567.6*** (171.5)    |
| as_factor(EDUCD_1950)999    | 764.4 (778.3)       | -90.31 (1,237.8)   | 1,050.4 (710.1)     |
| INCWAGE_1940                | 0.2196*** (0.0209)  | 0.3503*** (0.0472) | 0.2053*** (0.0219)  |
| as_factor(SEX_1950)2        |                     |                    | -475.4*** (38.30)   |
| ___________________________ | ___________________ | __________________ | ___________________ |
| S.E. type                   | IID                 | IID                | IID                 |
| Observations                | 5,387               | 3,605              | 6,558               |
| R2                          | 0.07517             | 0.06889            | 0.09119             |
| Adj. R2                     | 0.07086             | 0.06239            | 0.08772             |

** Migration
#+begin_src R
main_sample <- linked_data_full |>
  filter(birthyr < 1925) |>
  mutate(pr_intern = ifelse(RACE==4, 0, prI_county),
         pr_intern2 = ifelse(RACE==4, 0, prI_full),
         pr_intern3 = ifelse(RACE==4, 0, prI_AB),
         across(c("STATEFIP", "BPL", "OCC1950", "MIGRATE5", "URBAN", "FARM", "IND1950"), as_factor),
         ag_occ = str_detect(as_factor(OCC1950), "Farm"),
         ag_ind = str_detect(as_factor(OCC1950), "Agriculture"),
         migrate5 = ifelse(MIGRATE5 %in% c(2,3,4), 1, 0)
         ) |>
  pivot_wider(
    id_cols = c("id", "race", "sex", "pr_intern", "pr_intern2", "pr_intern3", "migrate10", "income_tot"),
    names_from = YEAR,
    values_from = c("age", "salary", "employed", "OCC1950",
                    "migrate5",
                    "URBAN", "FARM", "IND1950", "ag_occ", "ag_ind",
                    "OCCSCORE", "WKSWORK1", "yearsschool", "STATEFIP",
                    "county_med.salary", "county_pop", "county_pop.japanese")
  )
#+end_src

#+RESULTS:
#+begin_src R :colnames yes
etable(
  feols(
  migrate10 ~ pr_intern + age_1950 + age_1950^2,
  data = main_sample
  ),
  feols(
  migrate10 ~ pr_intern + age_1950 + age_1950^2,
  cluster = ~ STATEFIP_1950,
  data = main_sample
  ),
  feols(
  migrate10 ~ pr_intern + age_1950 + age_1950^2 + migrate5_1940,
  data = main_sample
  )
)
#+end_src

#+RESULTS:
|                 | feols(migrate10 ~ .. | feols(migrate10 ~ r.. | feols(migrate10 ~ .. |
|-----------------+----------------------+-----------------------+----------------------|
| Dependent Var.: | migrate10            | migrate10             | migrate10            |
|                 |                      |                       |                      |
| Constant        | 0.0492 (0.0462)      | 0.0492 (0.0445)       | 0.0488 (0.0462)      |
| raceJapanese    | 0.0326* (0.0132)     | 0.0326* (0.0158)      | 0.0330* (0.0133)     |
| pr_intern       | 0.0409* (0.0169)     | 0.0409 (0.0378)       | 0.0405* (0.0170)     |
| age_1950        | 0.0037. (0.0019)     | 0.0037* (0.0016)      | 0.0037. (0.0019)     |
| age_1950 square | -5.12e-5** (1.85e-5) | -5.12e-5*** (1.41e-5) | -5.14e-5** (1.86e-5) |
| _______________ | ____________________ | _____________________ | ____________________ |
| S.E. type       | IID                  | by: STATEFIP_1950     | IID                  |
| Observations    | 7,468                | 7,468                 | 7,462                |
| R2              | 0.01066              | 0.01066               | 0.01068              |
| Adj. R2         | 0.01013              | 0.01013               | 0.01014              |

** Logit model of migration indicator
#+begin_src R :colnames yes :results output
mig_logit <- glm(migrate10 ~ pr_intern + age_1950 + age_1950^2 + migrate5_1940,
    data = main_sample, family = "binomial")
modelsummary::modelsummary(mig_logit)
#+end_src

#+RESULTS:
#+begin_example

+-------------+-----------+
|             | (1)       |
+=============+===========+
| (Intercept) | -1.529    |
+-------------+-----------+
|             | (0.139)   |
+-------------+-----------+
| pr_intern   | 0.657     |
+-------------+-----------+
|             | (0.089)   |
+-------------+-----------+
| age_1950    | -0.013    |
+-------------+-----------+
|             | (0.003)   |
+-------------+-----------+
| Num.Obs.    | 7462      |
+-------------+-----------+
| AIC         | 5470.6    |
+-------------+-----------+
| BIC         | 5491.3    |
+-------------+-----------+
| Log.Lik.    | -2732.298 |
+-------------+-----------+
| RMSE        | 0.33      |
+-------------+-----------+
#+end_example

** County characteristics as outcome
#+begin_src R :colnames yes
etable(feols(
  c(county_med.salary_1950, county_pop_1950, county_pop.japanese_1950/county_pop_1950) ~  migrate10*pr_intern
    +  age_1950 + age_1950^2,
  cluster = ~STATEFIP_1950,
  data = main_sample)
  )
#+end_src

#+RESULTS:
|                       | feols(c(county_med...1 | feols(c(county_med.s..2 | feols(c(county_med.salary_1950, count..3 |
|-----------------------+------------------------+-------------------------+------------------------------------------|
| Dependent Var.:       | county_med.salary_1950 | county_pop_1950         | county_pop.japanese_1950/county_pop_1950 |
|                       |                        |                         |                                          |
| Constant              | 159.8 (98.63)          | 595,721.4. (311,508.4)  | 0.0069** (0.0024)                        |
| migrate10             | -82.31 (63.40)         | -262,720.0** (86,708.5) | 0.0009 (0.0008)                          |
| pr_intern             | -285.4** (82.08)       | 316,832.1 (211,197.0)   | 0.0148*** (0.0029)                       |
| age_1950              | 4.271* (1.613)         | 11,698.9 (11,120.7)     | 5.38e-5 (4.89e-5)                        |
| age_1950 square       | -0.0419* (0.0166)      | -127.4 (105.0)          | -6.62e-7 (4.75e-7)                       |
| migrate10 x pr_intern | 159.4. (85.56)         | -42,789.5 (138,270.8)   | -0.0077** (0.0024)                       |
| _____________________ | ______________________ | _______________________ | ______________________________           |
| S.E.: Clustered       | by: STATEFIP_1950      | by: STATEFIP_1950       | by: STATEFIP_1950                        |
| Observations          | 7,465                  | 7,465                   | 7,465                                    |
| R2                    | 0.15342                | 0.01975                 | 0.24314                                  |
| Adj. R2               | 0.15286                | 0.01909                 | 0.24263                                  |

** Occupations
#+begin_src R :colnames yes
etable(feols(
  ag_occ_1950 ~ pr_intern + age_1950 + age_1950^2 + ag_occ_1940,
  data =  main_sample)
  )
#+end_src

#+RESULTS:
|                 | feols(ag_occ_195.. |
|-----------------+--------------------|
| Dependent Var.: | ag_occ_1950        |
|                 |                    |
| Constant        | 0.0885* (0.0400)   |
| pr_intern       | 0.1054*** (0.0094) |
| age_1950        | -0.0005 (0.0016)   |
| age_1950 square | -1.3e-5 (1.61e-5)  |
| ag_occ_1940TRUE | 0.4488*** (0.0100) |
| _______________ | __________________ |
| S.E. type       | IID                |
| Observations    | 7,462              |
| R2              | 0.29127            |
| Adj. R2         | 0.29089            |


** Were internees moving out of the West Coast?
#+begin_src R :colnames yes
df |>
  filter(COUNTYICP_1940 != COUNTYICP_1950) |>
  mutate(WC_1940 = ifelse(STATEFIP_1940 %in% c(4,6,41,53), "West Coast", "Other"),
         WC_1950 = ifelse(STATEFIP_1950 %in% c(4,6,41,53), "West Coast", "Other"),
         japanese = ifelse(japanese==1, "Japanese", "Chinese") ) |>
  count(japanese, WC_1940, WC_1950) |>
  arrange(japanese, desc(n)) |>
  pivot_wider(names_from = japanese, values_from = n)
#+end_src

#+RESULTS:
| WC_1940    | WC_1950    | Chinese | Japanese |
|------------+------------+---------+----------|
| West Coast | West Coast |     258 |      376 |
| Other      | Other      |     109 |       57 |
| Other      | West Coast |      47 |       14 |
| West Coast | Other      |      26 |       76 |
