* Data Sources and Downloading
** WRA Camp Internee Records

The internee data file is available in the [[https://catalog.archives.gov/][National Archives]] catalog with the NAID 1264228.

I use the fixed-width text version of this text file from Jaime Arellano-Bover's online replication package at
https://www.openicpsr.org/openicpsr/project/144561/version/V1/view:
=WRA.FORM26.PU.txt=.

** County Codes Crosswalk
 =data/county_codes_cw.csv= contains the list of 1940 counties with their state and county codes in NHGIS and ICPSR form.
 It also includes crosswalk wieghts for any possible border changes between 1940 and 1950 generated using the method from [[https://fpeckert.me/eglp/][Eckert et al. (2020)]].
** Historical Census Microdata
:PROPERTIES:
:header-args:R: :session *R:ipums* :tangle R/download-ipums.R :colnames yes :export no
:END:
#+name: load-packages
#+begin_src R :results silent
library(ipumsr)
library(tidyverse)
#+end_src

I download linked full-count census microdata from the IPUMS [[https://usa.ipums.org/usa/mlp/mlp.shtml][Multigenerational Longitudinal Panel]] for the census years 1940 and 1950.
The main IPUMS variables I enclure are each respondant's county of residence at the time of being surveyed, as well as demographics including sex, birthyear, race, and birthplace.
#+name: download-lr-migration-data
#+begin_src R :results silent
ipums_samples <- c("us1940b", "us1950b")
vars <- list(
  var_spec("RACE", case_selections = c("4","5")), # Japanese and Chinese
  "STATEFIP", "STATEICP", "COUNTYICP", "ENUMDIST", "CITY", # geographic variables
  "SEX", "BIRTHYR", "MARST",# demographics
  var_spec("BPL", attached_characteristics = c("mother", "father")),
  var_spec("NATIVITY",  attached_characteristics = c("mother", "father", "spouse")),
  "CITIZEN",  "EDUC", # assimilation/culture
  "LABFORCE", "OCC1950", "EMPSTAT", # labor market status
  "OCCSCORE", "INCTOT", "INCWAGE", "INCBUSFM"
)
# download data using IPUMS API
internment_extract <- define_extract_micro(
  collection = "usa",
  description = "linked microdata for internee and control population from 1940 to 1950",
  samples = ipums_samples,
  variables = vars
) |>
  submit_extract() |>
  wait_for_extract() |>
  download_extract("data/fullcount_census")
#+end_src

To use the latest versions of the MLP linkages from IPUMS, I download the crosswalk files as csv's from https://usa.ipums.org/usa/mlp/mlp_census_crosswalks.shtml.

Microdata extracted from IPUMS using =ipumsr::download_extract()= function
downloads both the compressed data file (e.g., =usa_00122.dat.gz=)
and the codebook ddi file which is used to label the variables (e.g., =usa_00122.xml=).

For this project, the files needed are located in the =data/= subdirectory:
#+begin_example
├── data/
│   ├── mlp_1940_1950_v1_2_csv
│   │   ├── mlp_1940_1950_v1.2.csv
│   │   └── README_mlp_csv.txt
│   ├── nhgis0032_shape.zip
│   ├── usa_00123.dat.gz
│   ├── usa_00123.xml
│   └── ...
#+end_example

** MLP Crosswalk Links
:PROPERTIES:
:HEADER-ARGS:R: :session *R:ipums* :tangle R/write-db.R :results silent
:END:

The original micro data files from IPUMS are too large to fit in memory,
and the MLP v1.2 linkages are provided as crosswalks which have to be joined to the data.
I first read both crosswalks and extract microdata into a local database file
so that I can use SQL operations via the =duckdb= API in R.

#+name: define-objects
#+begin_src R
# open database connection with duckdb
library(ipumsr)
library(dplyr)
library(dbplyr)
library(duckdb)
database <- dbConnect(duckdb(), dbdir = "data/ipums_db.duckdb")
# data extract file
extract <- "data/fullcount_census/usa_00124.xml"
ddi <- read_ipums_ddi(extract)
# table name in database
tbl <- "ipums_microdata"
# crosswalk files for each adjacent census year pair
cw45_csv <- "data/fullcount_census/mlp_1940_1950_v1_2_csv/mlp_1940_1950_v1.2.csv"
#+end_src

*** Database Reading
To manage how much memory is used at once, I read the ddi file in chunks to the database as its own table.
I also read the crosswalks in as separate tables in the database.

#+name: write-database
#+begin_src R :eval false
# read in ipums extract to database in chunks
read_ipums_micro_chunked(
  ddi, # path to ddi .xml file in same location as data download
  callback = readr::SideEffectChunkCallback$new(
    function(x, pos) {
      if (pos == 1) {
        dbWriteTable(database, tbl, x, overwrite = TRUE)
      } else {
        dbWriteTable(database, tbl, x, overwrite = FALSE, append = TRUE)
      }
    }
  ),
  chunk_size = 1e7 # observations to read per chunk
)
#+end_src

#+begin_src R :eval false
# read crosswalk csv files into database
duckdb_read_csv(database, "mlp_crosswalks", cw45_csv)
#+end_src
* Data Cleaning
** Clean WRA camp records
:PROPERTIES:
:HEADER-ARGS:R: :tangle R/compile_WRA.R :session *R:internment*
:END:
Here is a version of Arellano-Bover's original Stata code to process the WRA form 26 data,
rewritten in R.
The file =WRA.FORM26.PU.txt= is read into R as fixed width data using =read_fwf= from the =readr= package.
*** Variables Names and Labels
#+begin_src R
#------------------------------------------------------------------------------#
#                               README                                         #
# this file was translated from the original stata do file compile_wra.do      #
# from the replication files for "displacement, diversity, and mobility:       #
# careeer impacts of japanese american internment" by jaime arellano-bover     #
# posted here: https://www.jarellanobover.com/research                         #
# translation was helped by the stata to r code translator chatgpt model by    #
# joseph noonan https://chatgpt.com/g/g-ddlktfvbt-stata-to-r-code-translator   #
#------------------------------------------------------------------------------#

library(tidyverse)
library(haven)  # for reading stata data_raw files

# Load dataset
path <- "~/Research/Internment/data/"
#+end_src

#+RESULTS:
: ~/Research/Internment/data/


The original form included internee's names, the assembly center and WRA camp they were first assigned to,
the county and city of thier previous address before being brought to the assembly centers,
as well as demographic information such as their education attainment, birthplace and year, occupation, and father's characteristics.

#+begin_src R :results silent 
# variables defined by column ranges in original file
column_positions <- fwf_widths(
  c(10,             8,                 1,             1,                 1,
    5,              1,                 1,             1,                 1,
    1,              1,                 2,             1,                 1,
    1,              1,                 6,             1,                 1,
    2,              2,                 1,             1,                 1,
    1,              3,                 3,             3,                 3,
    3,              6,                 5),
  col_names =
  c("last_name",    "first_name",      "initial",     "camp",            "assembly",
    "prev_address", "brth_cntry_pnts", "fath_occ_us", "fath_occ_abroad", "school_jap",
    "school_jap2",  "high_educ",       "arrival_us",  "length_jap",      "times_jap",
    "age_jap",      "military",        "ind_number",  "sex_marrge",      "race",
    "birth_yr",     "birthplace",      "japsch_ssn",  "educ",            "lang",
    "rel",          "qual_occ_1",      "qual_occ_2",  "qual_occ_3",      "pot_occ_1",
    "pot_occ_2",    "file_no",         "file_no_2"))

fw_data <- read_fwf(paste0(path, "WRA.FORM26.PU.txt"), column_positions)
#+end_src

There are some rows which need to be removed due to mistakenly inserted formatting rows and duplicate records.
#+begin_src R :results silent
data_raw <- fw_data |>
  filter(ind_number != "") |> # Drop records with empty ind_number
  # Handle duplicates
  group_by(ind_number, file_no, first_name, last_name) |>
  mutate(dup_n = row_number(), .after = last_name) |>
  ungroup() |>
  filter(dup_n == 1) |>
  select(-dup_n)
#+end_src

Add clean up demographic variables and label according to documentation.
#+begin_src R :results silent
data_labelled <- data_raw |>
  mutate(
    camp = labelled(as.integer(camp),
                    c("Manzanar"       = 1,
                      "Poston"         = 2,
                      "Gila River"     = 3,
                      "Tule Lake"      = 4,
                      "Minidoka"       = 5,
                      "Topaz"          = 6,
                      "Heart Mountain" = 7,
                      "Granada"        = 8,
                      "Rohwer"         = 9,
                      "Jerome"         = 10 )
                    ),
    assembly = case_when(assembly == "-" ~ "10",
                         assembly == "A" ~ "11",
                         assembly == "B" ~ "12",
                         assembly == "C" ~ "13",
                         assembly == "D" ~ "14",
                         assembly == "E" ~ "15",
                         assembly == "F" ~ "16",
                         assembly %in% c("T", "Z") ~ "",
                         .default = assembly),
    assembly = labelled(as.integer(assembly),
                        c("none"        = 0 , 
                          "Manzanar"    = 1 , 
                          "Fresno"      = 2 , 
                          "Marysville"  = 3 , 
                          "Mayor"       = 4 , 
                          "Merced"      = 5 , 
                          "Pinedale"    = 6 , 
                          "Pomona"      = 7 , 
                          "Portland"    = 8 , 
                          "Puyallup"    = 9 , 
                          "Sacramento"  = 10, 
                          "Salinas"     = 11, 
                          "Santa Anita" = 12, 
                          "Stockton"    = 13, 
                          "Tanforan"    = 14, 
                          "Tulare"      = 15, 
                          "Turlock"     = 16 )
                        ),
    sex = case_when(sex_marrge %in% c("1", "2", "3", "4", "5", "0") ~ 1, # men
                    sex_marrge %in% c("6", "7", "8", "9", "-", "&") ~ 2, # women
                    .default = NA),
    sex = labelled(as.integer(sex), c("male" = 1, "female" = 2)),
    marst = case_when(sex_marrge %in% c("1", "6") ~ 1, # single
                      sex_marrge %in% c("2", "9") ~ 2, # married
                      sex_marrge %in% c("3", "8") ~ 3, # widowed
                      sex_marrge %in% c("4", "9") ~ 4, # divorced
                      sex_marrge == "5" ~ 5, # separated
                      .default = NA),
    marst = labelled(as.integer(marst), c("single" = 1,
                                          "married" = 2,
                                          "widowed" = 3,
                                          "divorced" = 4,
                                          "separated" = 5)),
    birthyr = if_else(as.integer(birth_yr) > 42,
                      as.integer(birth_yr) + 1800, # born after 1842
                      as.integer(birth_yr) + 1900), # born before or during 1942
    race = case_when(race %in% c("4", "7", "L", "O", "V", "5", "J", "M", "P", "W", "6", "K", "N", "Q", "X") ~ 5, # japanese including mixed-race
                     race %in% c("8", "S", "T", "U") ~ 1, # white non-japanese 
                     race %in% c("1", "2", NA) ~ NA), # other race or not specified
    race = labelled(race, c("White" = 1, "Japanese" = 5)),
    bpl_pop = case_when(brth_cntry_pnts %in% c("B", "1", "4", "7", "C") ~ 501, # japan
                        brth_cntry_pnts %in% c("K", "2", "5", "8", "L") ~ 99, # US not specified
                        brth_cntry_pnts %in% c("T", "3", "6", "9", "U") ~ 15, # Hawaii
                        .default = NA), # Hawaii
    bpl_pop = labelled(bpl_pop, c("Japan" = 501, "United States, ns" = 99, "Hawaii" = 15)),
    bpl_mom = case_when(brth_cntry_pnts %in% c("A", "1", "2", "3", "D") ~ 501, # japan
                        brth_cntry_pnts %in% c("J", "4", "5", "6", "M") ~ 99, # US not specified
                        brth_cntry_pnts %in% c("S", "7", "8", "9", "V") ~ 15, # Hawaii
                        .default = NA), # Hawaii
    bpl_mom = labelled(bpl_mom, c("Japan" = 501, "United States, ns" = 99, "Hawaii" = 15)),
    yr_immig = if_else(as.integer(birth_yr) > 42,
                       as.integer(birth_yr) + 1800, # arrived after 1842
                       as.integer(birth_yr) + 1900), # arrived before or during 1942
    nativity = case_when(
      bpl_pop == 1 & bpl_mom == 1 ~ 1,  # both parents native-born
      bpl_pop == 2 & bpl_mom == 1 ~ 2,  # foreign father, native mother
      bpl_pop == 1 & bpl_mom == 2 ~ 3,  # native father, foreign mother
      bpl_pop == 2 & bpl_mom == 2 ~ 4,  # both parents foreign-born
      birthplace %in% 0:74 ~ 5,       # is foreign born themselves
      TRUE ~ NA_real_                    # for any other cases, assign NA
    ),
    educ_bach = ifelse(educ %in% c("A", "B", "C", "D", "E", "F", "G", "H", "I", "4"), 1, 0),
    bpl = case_when(
      birthplace == 31 ~ 001,  # Alabama	
      birthplace == 81 ~ 002,  # Alaska
      birthplace == 26 ~ 004,  # Arizona
      birthplace == 32 ~ 005,  # Arkansas
      birthplace == 13 ~ 006,  # California
      birthplace == 22 ~ 008,  # Colorado
      birthplace == 61 ~ 009,  # Connecticut
      birthplace == 52 ~ 010,  # Delaware
      birthplace == 51 ~ 011,  # District of Columbia
      birthplace == 53 ~ 012,  # Florida
      birthplace == 54 ~ 013,  # Georgia
      birthplace %in% 70:74 ~ 015,  # Hawaii
      birthplace == 23 ~ 016,  # Idaho
      birthplace == 41 ~ 017,  # Illinois
      birthplace == 42 ~ 018,  # Indiana
      birthplace == 43 ~ 019,  # Iowa
      birthplace == 44 ~ 020,  # Kansas
      birthplace == 33 ~ 021,  # Kentucky
      birthplace == 34 ~ 022,  # Louisiana
      birthplace == 62 ~ 023,  # Maine
      birthplace == 55 ~ 024,  # Maryland
      birthplace == 63 ~ 025,  # Massachusetts
      birthplace == 45 ~ 026,  # Michigan
      birthplace == 46 ~ 027,  # Minnesota
      birthplace == 35 ~ 028,  # Mississippi
      birthplace == 47 ~ 029,  # Missouri
      birthplace == 24 ~ 030,  # Montana
      birthplace == 48 ~ 031,  # Nebraska
      birthplace == 25 ~ 032,  # Nevada
      birthplace == 64 ~ 033,  # New Hampshire
      birthplace == 56 ~ 034,  # New Jersey
      birthplace == 21 ~ 035,  # New Mexico
      birthplace == 57 ~ 036,  # New York
      birthplace == 58 ~ 037,  # North Carolin
      birthplace == 49 ~ 038,  # North Dakota
      birthplace == 40 ~ 039,  # Ohio
      birthplace == 36 ~ 040,  # Oklahoma
      birthplace == 12 ~ 041,  # Oregon
      birthplace == 59 ~ 042,  # Pennsylvania
      birthplace == 65 ~ 044,  # Rhode Island
      birthplace == 50 ~ 045,  # South Carolina
      birthplace == "4-" ~ 046,  # South Dakota
      birthplace == 37 ~ 047,  # Tennessee
      birthplace == 38 ~ 048,  # Texas
      birthplace == 27 ~ 049,  # Utah
      birthplace == 66 ~ 050,  # Vermont
      birthplace == "5&" ~ 051,  # Virginia
      birthplace == 11 ~ 053,  # Washington
      birthplace == "5-" ~ 054,  # West Virginia
      birthplace == "4-" ~ 055,  # Wisconsin
      birthplace == 28 ~ 056,  # Wyoming
      birthplace == 0 ~ 099,  # United States, ns
      birthplace %in% 90:99 ~ 501, # Japan
      birthplace == 82 ~ 150,  # Canada
      birthplace == 83 ~ 200, # Mexico
      birthplace == 84 ~ 300, # South America
      .default = NA
    ),
  )
#+end_src
*** Previous Address
Group the internees into observable counties.
#+begin_src R :results silent
# previous address codes transcribed from WRA form 26 documentation
wra_counties <- read_csv("data/WRA_prev_address_list.csv")
#+end_src

The county names from the WRA records should match the county names from the NHGIS system for counties in 1940.
#+begin_src R :results silent
nhgis_codes <- read_csv("data/county_codes_cw.csv") |>
  distinct(STATENAM, NHGISNAM, NHGISST, NHGISCTY)

join_counties <- left_join(wra_counties, nhgis_codes,
                           by = c("state" = "STATENAM", "county" = "NHGISNAM") ) 
#+end_src

#+begin_src R
data_int <- data_labelled |>
  left_join(join_counties, by = "prev_address") |>
  select(ind_number, state, county, NHGISST, NHGISCTY,
         camp, assembly, race, sex, birthyr, bpl, bpl_pop, bpl_mom, yr_immig, nativity,
         last_name, first_name)
#+end_src

#+RESULTS:

*** Internee Demographic Groups
#+begin_src R
intrn_grps <- data_int |>
  filter(!is.na(state)) |>
  count(state, county, NHGISST, NHGISCTY, sex, birthyr, bpl) |>
  mutate(p = n / sum(n))

write_csv(intrn_grps, file = "data/internment_groups.csv")

intrn_grps |>
  arrange(desc(n)) |>
  head(n=25) |> 
  knitr::kable(format = "org")
#+end_src

#+RESULTS:
|   | state                                                                          | county      | NHGISST | NHGISCTY | sex | birthyr | bpl |   n |         p |
|   | :----------+:-----------+:-------+:--------+---:+-------:+---:+---:+---------: |             |         |          |     |         |     |     |           |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1921 |   6 | 458 | 0.0042262 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1923 |   6 | 458 | 0.0042262 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1921 |   6 | 447 | 0.0041247 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1922 |   6 | 443 | 0.0040878 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1925 |   6 | 420 | 0.0038755 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1925 |   6 | 411 | 0.0037925 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1923 |   6 | 405 | 0.0037371 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1920 |   6 | 403 | 0.0037187 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1924 |   6 | 398 | 0.0036725 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1922 |   6 | 390 | 0.0035987 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1924 |   6 | 384 | 0.0035434 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1920 |   6 | 381 | 0.0035157 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1919 |   6 | 375 | 0.0034603 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1888 | 501 | 370 | 0.0034142 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1926 |   6 | 364 | 0.0033588 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1926 |   6 | 343 |  0.003165 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1941 |   6 | 334 |  0.003082 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1918 |   6 | 330 | 0.0030451 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1927 |   6 | 328 | 0.0030266 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1917 |   6 | 302 | 0.0027867 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1886 | 501 | 294 | 0.0027129 |
|   | California                                                                     | Los Angeles |      60 |      370 |   2 |    1927 |   6 | 293 | 0.0027037 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1940 |   6 | 287 | 0.0026483 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1928 |   6 | 285 | 0.0026298 |
|   | California                                                                     | Los Angeles |      60 |      370 |   1 |    1887 | 501 | 284 | 0.0026206 |

** 1940 County-Level Japanese Population
:PROPERTIES:
:HEADER-ARGS:R: :session *R:internment* :tangle R/predict-internment.R :results silent
:END:
#+begin_src R
library(ipumsr)
library(dbplyr)
library(duckdb)
# data extract file
db <- dbConnect(duckdb(), dbdir = "data/ipums_db.duckdb")
tbl = "ipums_microdata"

dt40 <- tbl(db, tbl) |>
  filter(YEAR == 1940, RACE == 5) |>
  select(STATEFIP, COUNTYICP, SEX, BIRTHYR, BPL)
#+end_src

#+RESULTS:

Collect all Japanese-American micro-records by county, sex, birthyear, and birthplace groups.

#+begin_src R
JApop_groups <- dt40 |>
  count(STATEFIP, COUNTYICP, SEX, BIRTHYR, BPL) |>
  collect() |>
  mutate(
    # proportion in each demographic group
    p = n / sum(n),
    # state-county geography code based on NHGIS
    NHGISST = str_pad(string = STATEFIP*10, width = 3, side = "left", pad = "0"),
    NHGISCTY = str_pad(COUNTYICP, width = 4, side = "left", pad = "0") )

# save results
readr::write_csv(JApop_groups, file = "data/ja_pop_groups.csv")
#+end_src

** MLP Linked Microrecords
:PROPERTIES:
:HEADER-ARGS:R: :session *R:internment* :tangle R/link-census.R :results silent
:END:
Sample
At this stage, I only need the state and county of each person who is linked across census years.
For each decade-to-decade comparison (1920 to 1930, and 1930 to 1940),
I join the state and county location by =HISTID= code for the appropriate year in the crosswalk file.
Then I count how many linked individuals appear in each county-county migration group
and drop individuals who do not report a county location in either decade. 

#+begin_src R
# open database connection with duckdb
library(ipumsr)
library(dplyr)
library(dbplyr)
library(duckdb)
database <- dbConnect(duckdb(), dbdir = "data/ipums_db.duckdb")
tbl <- "ipums_microdata"
# bring needed microdata into a tibble for joining
d1 <- tbl(database, tbl) |>
  filter(YEAR == 1940) # decade start year
d2 <- tbl(database, tbl) |>
  filter(YEAR == 1950) # decade end year

# histid to be used in appropriate cw file
cw <- tbl(database, "mlp_crosswalks")

# join histids to selected data from year 1
l1 <- cw |>
  inner_join(d1, by = c("histid_1940" = "HISTID")) |>
  collect()

# join histids to selected data from year 2
l2 <- cw |>  
  inner_join(d2, by = c("histid_1950" = "HISTID")) |>
  collect()
#+end_src

#+begin_src R
# join all selected data between years by crosswalked histids
results <- bind_rows(l1, l2) |>
  # get rid of leftover linking and technical varibles
  select(!c("step", "SAMPLE", "SERIAL", "HHWT", "PERWT", 
            "PERNUM", "GQ", "VERSIONHIST", "CITY", "ENUMDIST"))

# generate new unique ids for each linked person
histid_pairs <- results |>
  count(histid_1940, histid_1950) |>
  filter(n>1) |> # multiple matches
  mutate(id = row_number()) |>
  select(!n)

results <- results |>
  left_join(histid_pairs, by = c("histid_1940", "histid_1950")) |>
  filter(!is.na(id)) |>
  select(!c("histid_1940", "histid_1950")) |>
  relocate(id)

# clean up other variables
results <- results |>
  mutate(
    # replace missing values with NAs and adjust all dollar amounts to 1940 levels
    across(c(INCWAGE, INCTOT, INCBUSFM)),
    ~ case_when(
      . %in% c(999999,999998) ~ NA,
      YEAR == 1950 ~ . * 0.59, # deflated dollars to 1940 standards
      .default = .
    ),
    married = ifelse(MARST %in% 1:2, 1, 0),
    foreign = ifelse(NATIVITY == 5, 1, 0),
    college = ifelse(EDUC %in% 7:11, 1, 0),
    employed = ifelse(EMPSTAT == 1, 1, 0),
    female = ifelse(SEX==2, 1, 0),
    OCC1950 = ifelse(OCC1950 %in% 979:999, NA, OCC1950),
  )
#+end_src

#+RESULTS:

#+name: write-linked-sample
#+begin_src R :exports results
readr::write_csv(results, file = "data/linked_census_sample.csv")
#+end_src

This procedure leaves me with a dataset of all MLP records of anyone reported as Japanese-American with links between the 1940 and 1950 census.
This is about 5,000 linked Japanese-American individuals with observable county locations in 1940 and 1950.

* Predicted Internment Status
:PROPERTIES:
:HEADER-ARGS:R: :tangle R/predict_internment.R :session *R:internment*
:END:

#+begin_src R :results silent
library(tidyverse)
#+end_src

 Estimating Predicted Internment Status using Bayes Rule:

$$Pr(I_i=1|Z_i,s_i^{40}) = \frac{Pr(z_i,s_i^{40}|I_i=1) \cdot Pr(I_i=1)}{Pr(z_i,s_i^{40})}$$

** $Pr(z_i,s_i^{40}|I_i=1)$ : proportion of internees with in each demographic group
For the time-invariant $z_i$ characteristics, I use the internees recorded county of residence, sex, birth year, birthplace, and race.
These internee demographic groups are save in the file =data/internment_groups.csv=.
#+begin_src R
# proportion of each demographic group in internee population
pr_z_I <- read_csv("data/internment_groups.csv")
#+end_src

#+RESULTS:

** $Pr(I_i=1)$ : Fraction of internees out of entire 1940 Japanese population
$$\frac{\text{number in WRA file}}{\text{number of JA in 1940 full-count census}}$$
There are a total of 126,701 individuals with a reported race of Japanese in the full-count 1940 census.
In the WRA records, there are 109,518 names of interned individuals.
However, of those 83 are reported as White and 920 are missing a race category.
Therefore, I use 108,525 as the numerator of the fraction above.
$\hat{E}[I_i] = \frac{108,525}{126,701} = 0.856544$
#+begin_src R
# proportion of 1940 Japanese population interned
pr_I <- 108525/126701
#+end_src

#+RESULTS:
: 0.8565441472443

** $Pr(z_i,s_i^{40})$: proportion of Japanese Americans in each demographic group in 1940 census
#+begin_src R
# proportion of each demographic group in 1940 Japanese population
pr_z <- read_csv("data/ja_pop_groups.csv")
#+end_src

#+RESULTS:
** Proportion of Predicted Internees in Each Demographic Group
Combine internee records with census records and calculate predicted internment probability using Bayes' Rule formulation from above:
#+begin_src R
# create county-by-demographic group level dataset
dt <- left_join(pr_z_I, pr_z,
                by = c("NHGISST", "NHGISCTY",
                       "sex"="SEX", "birthyr"="BIRTHYR", "bpl"="BPL"),
                suffix = c("_z_I","_z")) |> # internees or 1940 pop indicator
  # groups with no matching internee groups are assumed not interned
  mutate(pr_intern = ifelse(is.na(p_z_I), 0, (p_z_I * pr_I) / p_z)) 
#+end_src

#+RESULTS:

Save the resulting dataset of each county level demographic group with the internment proportions to file.
#+begin_src R
# save results to disk
write_csv(dt, file = "data/pr_intern_status.csv")
#+end_src

#+RESULTS:
