#+TITLE: Japanese Internment: outcomes of forced migration

This repository contains research materials for analyzing the economic outcomes of the Japanese Americans interned across the Western United States during World War II.

* Software

** R: Version 4.4.1
_packages_:

- =ipumsr= - version 0.8.1
- =tidyverse= - version 2.0.0
- =duckdb= - version 1.1.3-2
- =dbplyr= - version 2.5.0
- =fixest= - version 0.12.1
- =targets= - version 1.11.3

* Data Sources

See [[file:./data.org][the data documentation page]] for more details on the data cleaning and linking process.
The current datasets for this project are gathered from the following sources:

** IPUMS USA

All census records are downloaded from [[https://usa.ipums.org/usa/][IPUMS]] using the =ipumsr= R package via the [[https://developer.ipums.org/docs/v2/apiprogram/apis/microdata/#ipums-usa][IPUMS API]].

To download the data yourself, you will need to:

1. Create an IPUMS account at <https://usa.ipums.org/usa> (or make sure you are logged in and have access to IPUMS USA).

2. Get your own API key at <https://account.ipums.org/api_keys>

3. Install =ipumsr=:

#+begin_src R
install.packages("ipumsr")
#+end_src

4. Set your new API key in R:

Follow the instructions at <https://tech.popdata.org/ipumsr/articles/ipums-api.html#set-key>:

#+begin_src R
# Save key in .Renviron for use across sessions
set_ipums_api_key("paste-your-key-here", save = TRUE)
#+end_src

Once you have a working IPUMS API key, you should be able to run the R script [[file:./R/download-ipums.R]]
to download the exact same microdata I use.

For example:
#+begin_src sh
Rscript --vanilla ./R/download-ipums.R
#+end_src

Once the IPUMS download request has processed (it might take several hours),
the compressed data file and corresponding codebook file should download to the =data/fullcount_census= subdirectory of wherever you have cloned this repository locally.
If this doesn't work, you could also download the data through the IPUMS website and just make sure that you download to the correct location.

For example:
#+begin_example
data/fullcount_census/
├── usa_00124.dat.gz
└── usa_00124.xml
#+end_example

*** Linking Crosswalks

I utilise version 1.2 of the 1940-1950 census linkages created by the [[https://usa.ipums.org/usa/mlp/mlp_data_description.shtml][Multigenerational Longitudinal Panel]] (MLP) project at IPUMS.
The linkages for this version are only available as a crosswalk file which can be downloaded from https://usa.ipums.org/usa/mlp/mlp_data_description.shtml

I use the 10-year 1940-1950 CSV file to create the linked microdata sample of internees.

*** IPUMS Citation and Terms of Use

As part of the terms of using IPUMS data, I have copied their provided citations below:

Jonas Helgertz, Nesile Ozder, Steven Ruggles, John Robert Warren, Catherine A. Fitch, J. David Hacker, Matt A. Nelson, Joseph P. Price, Evan Roberts, and Matthew Sobek. IPUMS Multigenerational Longitudinal Panel: Version 1.2 [dataset]. Minneapolis, MN: IPUMS, 2024. https://doi.org/10.18128/D016.V1.2

Steven Ruggles, Matt A. Nelson, Matthew Sobek, Catherine A. Fitch, Ronald Goeken, J. David Hacker, Evan Roberts, and J. Robert Warren. IPUMS Ancestry Full Count Data: Version 4.0 [dataset]. Minneapolis, MN: IPUMS, 2024. https://doi.org/10.18128/D014.V4.0 

If you use the data yourself, be careful to not redistribute any of the actual linked micrdata records.

I do this by ignoring any of the downloaded data files and all intermediate data files which include individuan records from version control
in my [[file:.gitignore]] file.

** National Archives Catalog

The fixed-width text version of the original WRA internment camp records,
(together with the accompanying documentation) can be obtained from the online National Archive Catalog
(NAID 1264228).
I include a copy of the file in this repository: [[file:./data/WRA.FORM26.PU.txt]]
