:PROPERTIES:
:GPTEL_MODEL: anthropic/claude-sonnet-4
:GPTEL_BACKEND: OpenRouter
:GPTEL_SYSTEM: You are a large language model living in Emacs and a helpful assistant. Respond concisely.
:GPTEL_BOUNDS: ((response (5908 7115)))
:END:
#+PROPERTY: header-args:R :session *R* :colnames yes
#+TITLE: Aggregating total sample variance from chunked subsets

#+begin_src R :results silent
setwd("~/Documents/Work/Internment/notes")
library(tidyverse)
#+end_src

* Algorithm Description
I found a [[https://math.stackexchange.com/questions/3604607/can-i-work-out-the-variance-in-batchesmath][stackexchange answer]] giving the following formula for calculating the total variance in chunks of different sizes.
#+begin_quote
$$
s_T^2 =
\frac{ (n_i - 1) s_i^2 + (n_T - 1) s_T^2 }
{ n_i + n_T - 1} +
\frac{ n_i n_T (\bar{x_i} - \bar{x_T}^2}
{ (n_i + n_T) (n_i + n_T - 1) }
$$
1. Set i=1.
2. Compute $n_i$, $x_i$, and $s_{xi}^2$, the sample size, sample mean, and sample variance of dataset i.
3. Increment i.
4. Repeat Step 2.
5. Use the above two formulas to compute a new $n_T$, $x_T$, and $s_T^2$ representing the sample size, sample mean, and sample variance of all datasets up to set i.
6. If the last dataset was used to compute the result in step 5, stop. Otherwise, go to step 3.
#+end_quote

* Simplified Example
Here is an example dataset of our random variable of interest =x= for which we want to calculate the overall variance
in each of the groups represented by =g=.
#+begin_src R
data <- tibble(
  x = round(rnorm(mean = 0, sd = 1, n = 100), 2),
  g = sample(1:3, 100, replace = T)
)
head(data)
#+end_src

#+RESULTS:
|     x | g |
|-------+---|
|  1.58 | 2 |
|  0.36 | 1 |
| -0.28 | 1 |
|  0.51 | 2 |
|  0.39 | 3 |
| -0.29 | 2 |

Suppose that the original dataframe was too large to fit in memory, but we managed to calculate summary statistics on these individual chunks.
The chunks can be of different sample sizes represented by =n_i= for the number of observations in each of the =i= chunks.

#+begin_src R
chunk_sumstats <- data |>
  mutate(chunk = rep(1:10, each=10)) |>
  group_by(chunk, g) |>
  summarise(
    xbar = mean(x, na.rm = T),
    var  = var(x, na.rm = T),
    n    = n()
  )
#+end_src

#+RESULTS:
| chunk | g |                xbar |                var | n |
|-------+---+---------------------+--------------------+---|
|     1 | 1 |             -0.2075 |  0.294091666666667 | 4 |
|     1 | 2 |              0.0725 |   1.69989166666667 | 4 |
|     1 | 3 |               -0.96 |              3.645 | 2 |
|     2 | 1 |               -0.03 |             1.1452 | 3 |
|     2 | 2 |               0.534 |            1.77428 | 5 |
|     2 | 3 |              -0.595 |            1.46205 | 2 |
|     3 | 1 |               -1.44 |                    | 1 |
|     3 | 2 |  -0.246666666666667 |   1.42698666666667 | 6 |
|     3 | 3 |   0.543333333333333 | 0.0532333333333333 | 3 |
|     4 | 1 |              -0.106 |            3.36908 | 5 |
|     4 | 2 |               0.325 |            0.29645 | 2 |
|     4 | 3 |                0.42 |             1.1701 | 3 |
|     5 | 1 |              -0.895 |   2.33556666666667 | 4 |
|     5 | 2 | -0.0666666666666667 |   2.18543333333333 | 3 |
|     5 | 3 |  0.0733333333333333 |  0.202533333333333 | 3 |
|     6 | 1 |  -0.123333333333333 |  0.520946666666667 | 6 |
|     6 | 2 |               -0.52 |              1.445 | 2 |
|     6 | 3 |                0.07 |             0.2178 | 2 |
|     7 | 1 |                0.44 |             0.8263 | 3 |
|     7 | 2 |   0.646666666666667 |   1.35403333333333 | 3 |
|     7 | 3 | 0.00749999999999999 |           0.855825 | 4 |
|     8 | 1 |               0.052 |            0.42517 | 5 |
|     8 | 2 |               -0.53 |                    | 1 |
|     8 | 3 |                0.19 |  0.615266666666667 | 4 |
|     9 | 1 |               -0.43 |                    | 1 |
|     9 | 2 |   0.643333333333333 |   1.58503333333333 | 3 |
|     9 | 3 |               -0.24 |            0.77168 | 6 |
|    10 | 1 |  0.0766666666666667 |  0.181233333333333 | 3 |
|    10 | 2 |   0.166666666666667 |   2.43363333333333 | 3 |
|    10 | 3 |             -0.5025 |  0.783358333333333 | 4 |

Here is my application of this algorithm in R.
To match the format of my chunked dataset, it takes a tibble with chunked summary statistics.
#+begin_src R 
# Function to combine two statistics (Welford's online variance formula)
combine_var <- function(stat1, stat2) {
  n1 <- stat1$n; x1 <- stat1$mean; sx1 <- stat1$var
  n2 <- stat2$n; x2 <- stat2$mean; sx2 <- stat2$var
  
  n_combined <- n1 + n2
  mean_combined <- (n1 * x1 + n2 * x2) / n_combined
  var_combined <- ((n1 - 1) * sx1 + (n2 - 1) * sx2) / (n_combined - 1) + 
                  n1 * n2 * (x1 - x2)^2 / (n_combined * (n_combined - 1))
  
  list(n = n_combined, mean = mean_combined, var = var_combined)
}

# apply combine_var over subsample sum stats
total_var <- function(chunks, n, mean, var, groups) {
  library(purrr)
  cumulative_stats <- chunks |>
    # if group only has one observation, drop it
    filter({{n}} > 1) |>
    group_by({{ groups }}) |>
    mutate(
      stats = map(row_number(),
                  ~ list(n = {{n}}[.x],
                         mean = {{mean}}[.x],
                         var = {{var}}[.x])
                  )
      ) |>
    pull(stats) |>
    accumulate(combine_var,
               .init = list(
                 n = 0,
                 mean = 0,
                 var = 0)) |>
    tail(-1) |>
    map_dfr(~ tibble(n = .x$n, mean = .x$mean, var = .x$var),
            .id = "cumulative_step")

  cumulative_stats
}

steps <- total_var(chunk_sumstats,
          n = n,
          mean = xbar,
          var = var,
          groups = g)
#+end_src

#+RESULTS:
| cumulative_step |  n |                 mean |               var |
|-----------------+----+----------------------+-------------------|
|               1 |  4 |              -0.2075 | 0.294091666666667 |
|               2 |  8 |              -0.0675 | 0.876964285714286 |
|               3 | 10 |               -0.246 |  1.22869333333333 |
|               4 | 13 |   -0.196153846153846 |  1.12135897435897 |
|               5 | 18 |  0.00666666666666667 |  1.32227058823529 |
|               6 | 20 |              -0.0535 |  1.29432921052632 |
|               7 | 26 |  -0.0980769230769231 |  1.27597615384615 |
|               8 | 29 |  -0.0317241379310345 |  1.18258620689655 |
|               9 | 34 |  -0.0426470588235294 |  1.41249278074866 |
|              10 | 36 |  -0.0222222222222222 |  1.34754349206349 |
|              11 | 39 |   0.0117948717948718 |  1.31699406207827 |
|              12 | 43 |  -0.0725581395348837 |  1.42941949058693 |
|              13 | 46 |  -0.0721739130434783 |  1.43125739130435 |
|              14 | 49 |   -0.063265306122449 |  1.35148494897959 |
|              15 | 55 |  -0.0698181818181818 |  1.24991292929293 |
|              16 | 57 |  -0.0856140350877193 |  1.23806077694236 |
|              17 | 59 |  -0.0803389830508475 |  1.19993091759205 |
|              18 | 62 |  -0.0551612903225807 |  1.18068112109995 |
|              19 | 65 |  -0.0227692307692308 |  1.18967346153846 |
|              20 | 69 |  -0.0210144927536232 |  1.15750042625746 |
|              21 | 74 |  -0.0160810810810811 |  1.10185703443169 |
|              22 | 78 | -0.00551282051282052 |   1.0706822011322 |
|              23 | 81 |   0.0185185185185185 |  1.08536027777778 |
|              24 | 87 | 0.000689655172413781 |  1.05884370489174 |
|              25 | 90 |  0.00322222222222221 |  1.02741309612984 |
|              26 | 93 |  0.00849462365591397 |  1.04765857877513 |
|              27 | 97 |  -0.0125773195876289 |  1.03891724656357 |

** Plot the results
#+begin_src R :results silent
plt_data <- steps |>
  mutate(step = as.integer(cumulative_step)) |>
  select(-cumulative_step) |>
  pivot_longer(cols = c("mean", "var"), names_to = "stat")

#+end_src

#+RESULTS:
#+begin_src R :exports results :results graphics file :file figures/tot_var_convergence.pdf
ggplot(aes(x = step, y = value, color = stat, group = stat), data = plt_data) +
  geom_line() +
  geom_hline(yintercept = mean(data$x), color = "red") +
  geom_hline(yintercept = var(data$x), color = "blue") +
  facet_wrap(~stat)
#+end_src

#+RESULTS:
[[file:figures/tot_var_convergence.pdf]]
