* Data Sources and Downloading
** County Codes Crosswalk
 =data/county_codes_cw.csv= contains the list of 1940 counties with their state and county codes in NHGIS and ICPSR form.
 It also includes crosswalk wieghts for any possible border changes between 1940 and 1950 generated using the method from [[https://fpeckert.me/eglp/][Eckert et al. (2020)]].
** Historical Census Microdata
:PROPERTIES:
:header-args:R: :session *R:ipums* :tangle R/download-ipums.R :colnames yes :export no
:END:
#+name: load-packages
#+begin_src R :results silent
library(ipumsr)
library(tidyverse)
#+end_src

I download linked full-count census microdata from the IPUMS [[https://usa.ipums.org/usa/mlp/mlp.shtml][Multigenerational Longitudinal Panel]] for the census years 1940 and 1950.
The main IPUMS variables I enclure are each respondant's county of residence at the time of being surveyed, as well as demographics including sex, birthyear, race, and birthplace.
#+name: download-lr-migration-data
#+begin_src R :results silent
ipums_samples <- c("us1940b", "us1950b")
vars = list(
  "STATEFIP", "STATEICP", "COUNTYICP", "ENUMDIST", "CITY", # geographic variables
  "SEX", "BIRTHYR", "RACE", "BPL", "MARST",# demographics
  "CITIZEN",  "EDUC", # assimilation/culture
  "LABFORCE", "OCC1950", "EMPSTAT", # labor market status
  var_spec("NATIVITY",  attached_characteristics = c("mother", "father", "spouse")),
  var_spec("OCCSCORE", attached_characteristics = c("mother", "father", "spouse")),
  var_spec("INCTOT", attached_characteristics = c("mother", "father", "spouse")),
  var_spec("INCWAGE", attached_characteristics = c("mother", "father", "spouse")),
  "INCBUSFM"
)
# download data using IPUMS API
lr_migration_extract <- define_extract_micro(
  collection = "usa",
  description = "linked microdata for internee and control population from 1940 to 1950",
  samples = ipums_samples,
  variables = vars
) |>
  submit_extract() |>
  wait_for_extract() |>
  download_extract("data")
#+end_src

To use the latest versions of the MLP linkages from IPUMS, I download the crosswalk files as csv's from https://usa.ipums.org/usa/mlp/mlp_census_crosswalks.shtml.

Microdata extracted from IPUMS using =ipumsr::download_extract()= function
downloads both the compressed data file (e.g., =usa_00122.dat.gz=)
and the codebook ddi file which is used to label the variables (e.g., =usa_00122.xml=).

For this project, the files needed are located in the =data/= subdirectory:
#+begin_example
├── data/
│   ├── mlp_1940_1950_v1_2_csv
│   │   ├── mlp_1940_1950_v1.2.csv
│   │   └── README_mlp_csv.txt
│   ├── nhgis0032_shape.zip
│   ├── usa_00123.dat.gz
│   ├── usa_00123.xml
│   └── ...
#+end_example

** WRA Camp Internee Records

The internee data file is available in the [[https://catalog.archives.gov/][National Archives]] catalog with the NAID 1264228.

I use the fixed-width text version of this text file from Jaime Arellano-Bover's online replication package at
https://www.openicpsr.org/openicpsr/project/144561/version/V1/view:
=WRA.FORM26.PU.txt=.

* Data Cleaning
** Clean WRA camp records
:PROPERTIES:
:HEADER-ARGS:R: :tangle R/compile_WRA.R :session *R:internment*
:END:
Here is a version of Arellano-Bover's original Stata code to process the WRA form 26 data,
rewritten in R.
The file =WRA.FORM26.PU.txt= is read into R as fixed width data using =read_fwf= from the =readr= package.
*** Variables Names and Labels
#+begin_src R
#------------------------------------------------------------------------------#
#                               README                                         #
# this file was translated from the original stata do file compile_wra.do      #
# from the replication files for "displacement, diversity, and mobility:       #
# careeer impacts of japanese american internment" by jaime arellano-bover     #
# posted here: https://www.jarellanobover.com/research                         #
# translation was helped by the stata to r code translator chatgpt model by    #
# joseph noonan https://chatgpt.com/g/g-ddlktfvbt-stata-to-r-code-translator   #
#------------------------------------------------------------------------------#

library(tidyverse)
library(haven)  # for reading stata data_raw files

# Load dataset
path <- "~/Research/Internment/data/"
#+end_src


The original form included internee's names, the assembly center and WRA camp they were first assigned to,
the county and city of thier previous address before being brought to the assembly centers,
as well as demographic information such as their education attainment, birthplace and year, occupation, and father's characteristics.

#+begin_src R :results silent 
# variables defined by column ranges in original file
column_positions <- fwf_widths(
  c(10,             8,                 1,             1,                 1,
    5,              1,                 1,             1,                 1,
    1,              1,                 2,             1,                 1,
    1,              1,                 6,             1,                 1,
    2,              2,                 1,             1,                 1,
    1,              3,                 3,             3,                 3,
    3,              6,                 5),
  col_names =
  c("last_name",    "first_name",      "initial",     "camp",            "assembly",
    "prev_address", "brth_cntry_pnts", "fath_occ_us", "fath_occ_abroad", "school_jap",
    "school_jap2",  "high_educ",       "arrival_us",  "length_jap",      "times_jap",
    "age_jap",      "military",        "ind_number",  "sex_marrge",      "race",
    "birth_yr",     "birthplace",      "japsch_ssn",  "educ",            "lang",
    "rel",          "qual_occ_1",      "qual_occ_2",  "qual_occ_3",      "pot_occ_1",
    "pot_occ_2",    "file_no",         "file_no_2"))

fw_data <- read_fwf(paste0(path, "WRA.FORM26.PU.txt"), column_positions)
#+end_src

There are some rows which need to be removed due to mistakenly inserted formatting rows and duplicate records.
#+begin_src R :results silent
data_raw <- fw_data |>
  filter(ind_number != "") |> # Drop records with empty ind_number
  # Handle duplicates
  group_by(ind_number, file_no, first_name, last_name) |>
  mutate(dup_n = row_number(), .after = last_name) |>
  ungroup() |>
  filter(dup_n == 1) |>
  select(-dup_n)
#+end_src

Add clean up demographic variables and label according to documentation.
#+begin_src R :results silent
data_labelled <- data_raw |>
  mutate(
    camp = labelled(as.integer(camp),
                    c("Manzanar"       = 1,
                      "Poston"         = 2,
                      "Gila River"     = 3,
                      "Tule Lake"      = 4,
                      "Minidoka"       = 5,
                      "Topaz"          = 6,
                      "Heart Mountain" = 7,
                      "Granada"        = 8,
                      "Rohwer"         = 9,
                      "Jerome"         = 10 )
                    ),
    assembly = case_when(assembly == "-" ~ "10",
                         assembly == "A" ~ "11",
                         assembly == "B" ~ "12",
                         assembly == "C" ~ "13",
                         assembly == "D" ~ "14",
                         assembly == "E" ~ "15",
                         assembly == "F" ~ "16",
                         assembly %in% c("T", "Z") ~ "",
                         .default = assembly),
    assembly = labelled(as.integer(assembly),
                        c("none"        = 0 , 
                          "Manzanar"    = 1 , 
                          "Fresno"      = 2 , 
                          "Marysville"  = 3 , 
                          "Mayor"       = 4 , 
                          "Merced"      = 5 , 
                          "Pinedale"    = 6 , 
                          "Pomona"      = 7 , 
                          "Portland"    = 8 , 
                          "Puyallup"    = 9 , 
                          "Sacramento"  = 10, 
                          "Salinas"     = 11, 
                          "Santa Anita" = 12, 
                          "Stockton"    = 13, 
                          "Tanforan"    = 14, 
                          "Tulare"      = 15, 
                          "Turlock"     = 16 )
                        ),
    sex = case_when(sex_marrge %in% c("1", "2", "3", "4", "5", "0") ~ 0, # men
                    sex_marrge %in% c("6", "7", "8", "9", "-", "&") ~ 1, # women
                    .default = NA),
    sex = labelled(as.integer(sex), c("male" = 0, "female" = 1)),
    marst = case_when(sex_marrge %in% c("1", "6") ~ 1, # single
                      sex_marrge %in% c("2", "9") ~ 2, # married
                      sex_marrge %in% c("3", "8") ~ 3, # widowed
                      sex_marrge %in% c("4", "9") ~ 4, # divorced
                      sex_marrge == "5" ~ 5, # separated
                      .default = NA),
    marst = labelled(as.integer(marst), c("single" = 1,
                                          "married" = 2,
                                          "widowed" = 3,
                                          "divorced" = 4,
                                          "separated" = 5)),
    birth_yr = if_else(as.integer(birth_yr) > 42,
                       as.integer(birth_yr) + 1800, # born after 1842
                       as.integer(birth_yr) + 1900), # born before or during 1942
  )
#+end_src
*** Previous Address
Group the internees into observable counties.
#+begin_src R
# previous address codes transcribed from WRA form 26 documentation
wra_counties <- read_csv("data/WRA_prev_address_list.csv")
#+end_src
The county names from the WRA records should match the county names from the NHGIS system for counties in 1940.
#+begin_src R
nhgis_codes <- read_csv("data/county_codes_cw.csv") |>
  select(STATENAM, NHGISNAM, weight, NHGISST, NHGISCTY, NHGISCTY_1950)

join_counties <- full_join(nhgis_codes, wra_counties,
                           by = c("STATENAM" = "state", "NHGISNAM" = "county"),
                           relationship = "many-to-many")
#+end_src

#+begin_src R
data_int <- data_labelled |>
  left_join(wra_counties, by = "prev_address")
#+end_src

Checking the results by county:
#+begin_src R
intrn_grps <- data_int |>
  filter(!is.na(state), !is.na(county)) |>
  count(state, county, sex, birth_yr)

write_csv(intrn_grps, file = "data/internment_groups.csv")

intrn_grps |>
  arrange(desc(n)) |>
  head(n=25) |> 
  knitr::kable(format = "org")
#+end_src

#+RESULTS:
|   | state                                        | county      | sex | birth_yr |   n |
|   | :----------+:-----------+---:+--------:+---: |             |     |          |     |
|   | California                                   | Los Angeles |   0 |     1921 | 565 |
|   | California                                   | Los Angeles |   1 |     1921 | 538 |
|   | California                                   | Los Angeles |   0 |     1922 | 528 |
|   | California                                   | Los Angeles |   0 |     1923 | 518 |
|   | California                                   | Los Angeles |   1 |     1920 | 493 |
|   | California                                   | Los Angeles |   1 |     1923 | 478 |
|   | California                                   | Los Angeles |   1 |     1919 | 475 |
|   | California                                   | Los Angeles |   0 |     1925 | 466 |
|   | California                                   | Los Angeles |   1 |     1925 | 460 |
|   | California                                   | Los Angeles |   0 |     1920 | 456 |
|   | California                                   | Los Angeles |   1 |     1922 | 456 |
|   | California                                   | Los Angeles |   1 |     1924 | 454 |
|   | California                                   | Los Angeles |   0 |     1924 | 428 |
|   | California                                   | Los Angeles |   1 |     1918 | 407 |
|   | California                                   | Los Angeles |   0 |     1926 | 402 |
|   | California                                   | Los Angeles |   1 |     1917 | 381 |
|   | California                                   | Los Angeles |   1 |     1926 | 380 |
|   | California                                   | Los Angeles |   0 |     1927 | 373 |
|   | California                                   | Los Angeles |   0 |     1888 | 372 |
|   | California                                   | Los Angeles |   1 |     1916 | 368 |
|   | California                                   | Los Angeles |   1 |     1915 | 362 |
|   | California                                   | Los Angeles |   0 |     1918 | 354 |
|   | California                                   | Los Angeles |   0 |     1919 | 347 |
|   | California                                   | Los Angeles |   0 |     1915 | 338 |
|   | California                                   | Los Angeles |   0 |     1941 | 337 |

** MLP Crosswalk Links
:PROPERTIES:
:HEADER-ARGS:R: :session *R:ipums* :tangle R/clean_fc-census.R :results silent
:END:

The original micro data files from IPUMS are too large to fit in memory,
and the MLP v1.2 linkages are provided as crosswalks which have to be joined to the data.
I first read both crosswalks and extract microdata into a local database file
so that I can use SQL operations via the =duckdb= API in R.

#+name: define-objects
#+begin_src R
# open database connection with duckdb
library(ipumsr)
library(data.table)
library(dplyr)
library(dtplyr)
library(dbplyr)
library(duckdb)
database <- dbConnect(duckdb(), dbdir = "data/ipums_db.duckdb")
# data extract file
extract <- "data/fullcount_census/usa_00123.xml"
ddi <- read_ipums_ddi(extract)
# table name in database
tbl <- "ipums_microdata"
# crosswalk files for each adjacent census year pair
cw45_csv <- "data/mlp_1940_1950_v1_2_csv/mlp_1940_1950_v1.2.csv"
#+end_src

*** Database Reading
To manage how much memory is used at once, I read the ddi file in chunks to the database as its own table.
I also read the crosswalks in as separate tables in the database.

#+name: write-database
#+begin_src R 
# read in ipums extract to database in chunks
read_ipums_micro_chunked(
  ddi, # path to ddi .xml file in same location as data download
  callback = readr::SideEffectChunkCallback$new(
    function(x, pos) {
      if (pos == 1) {
        dbWriteTable(database, tbl, x, overwrite = TRUE)
      } else {
        dbWriteTable(database, tbl, x, overwrite = FALSE, append = TRUE)
      }
    }
  ),
  chunk_size = 1e7 # observations to read per chunk
)
#+end_src

#+begin_src R
# read crosswalk csv files into database
duckdb_read_csv(database, "mlp_crosswalks", cw45_csv)
#+end_src
** MLP Linked Microrecords Sample
At this stage, I only need the state and county of each person who is linked across census years.
For each decade-to-decade comparison (1920 to 1930, and 1930 to 1940),
I join the state and county location by =HISTID= code for the appropriate year in the crosswalk file.
Then I count how many linked individuals appear in each county-county migration group
and drop individuals who do not report a county location in either decade. 

***** TODO Rewrite this function to group by demographic categories
#+begin_src R
link_internee <- function(
  db_file = database, # your DuckDB connection
  dt_table,             # microdata table in DB
  cw_table,             # name of crosswalk table in DB, e.g. "cw_1920_1930"
  yr1, yr2,             # start and end year of each decade
  histid1, histid2,     # e.g. "histid_1920", "histid_1930"
  out_csv = NULL        # optional path to write csv
) {
  # open the database connection
  db <- dbConnect(duckdb(), dbdir = db_file)
  # bring needed microdata into a tibble for joining
  d1 <- tbl(db, dt_table) |>
    filter(YEAR == yr1, RACE == 5) |> # decade start year
    select(
      HISTID, STATEFIP, COUNTYICP, ENUMDIST, CITY, SEX, MARST, BIRTHYR, RACE, SEX, LABFORCE, INCWAGE, OCC1950, EDUC, CITIZEN, NATIVITY, NATIVITY_MOM, NATIVITY_POP
    )
  d2 <- tbl(db, dt_table) |>
    filter(YEAR == yr2, RACE == 5) |> # decade end year
    select(
      # make variable selection for linked dataset
      HISTID, STATEFIP, COUNTYICP, CITY, SEX, MARST, BIRTHYR, RACE, SEX, LABFORCE, INCWAGE, INCTOT, OCC1950, EDUC, CITIZEN, NATIVITY, NATIVITY_MOM, NATIVITY_POP
    )
  # histid to be used in appropriate cw file
  cw <- tbl(db, cw_table) |>
    rename(hid1 = paste("histid", yr1, sep = "_"), hid2 = paste("histid", yr2, sep = "_"))
  # join histids to selected data from year 1
  l1 <- d1 |>
    rename(hid1 = HISTID) |>
    inner_join(cw, by = "hid1")
  # join histids to selected data from year 2
  l2 <- d2 |>  
    rename(hid2 = HISTID) |>
    inner_join(cw, by = "hid2")
  # join all selected data between years by crosswalked histids
  results <- full_join(l1, l2, by = c("hid1", "hid2"), suffix = c("_1940", "_1950")) |>
    # get rid of leftover linking varibles
    select(!c("hid1", "hid2")) |>
    collect()
  
  if (!is.null(out_csv)) {
    write.csv(results, out_csv, row.names = FALSE)
  }
  
  return(results)
}
#+end_src

***** Apply decade-level summary function to all years
#+name: link-locations
#+begin_src R :exports results
# 1940 -> 1950
internee_data <- link_internee(
  db_file  = "data/ipums_db.duckdb",
  dt_table = "ipums_microdata",
  cw_table = "mlp_crosswalks",
  yr1      = 1940,
  yr2      = 1950,
  histid1  = "histid_1940",
  histid2  = "histid_1950",
  out_csv  = NULL
)

readr::write_csv(internee_data, file = "data/linked_internee_sample.csv")
#+end_src

This procedure leaves me with a dataset of all MLP records of anyone reported as Japanese-American with links between the 1940 and 1950 census.
This is about 5,000 linked Japanese-American individuals with observable county locations in 1940 and 1950.

